### PR TITLE
Update jenkins plugins 

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1542

### CODE REVIEW

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
Test FAILed.

**Comment by kris-lab** [comment]
Test PASSed.

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
Test PASSed.

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
Test PASSed.

**Comment by kris-lab** [comment]
Test PASSed.

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
@njam please have a look. Specs run locally. It also runs on CI, but due to network problems it never finish.

**Comment by kris-lab** [comment]
retest this please

**Comment by njam** [comment]
lgtm

**Pull request merged**
