### PR TITLE
First successful build on ubuntu 1504, git and polipo module

### PR DESCRIPTION
**Pull request by ppp0**
Goal: `bundle exec rake spec:git` to complete successfully

Needs some adaptations to e.g. puppet apt sources, polipo, what not

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
`if (echo 'wheezy trusty precise utopic' | grep -q <%= @lsbdistcodename %>); then` - should we rather do opposite way? So we install `puppetlabs-release-pc1` only if we match specific platform?

**Comment by ppp0** [comment]
we do for now..

* vivid is still available as `pr1` only even though `1510` is also out now
* as said, `1510` is now official, `1604` in the making.. 

It is likely that we will have to use `pr1` for future Ubuntus, too...

**Comment by ppp0** [comment]
@kris-lab now?

**Comment by ppp0** [comment]
I also adapted specs for `git`module to run on both wheezy and vivid

**Comment by kris-lab** [comment]
Also `-eq` will not work with string? It should be `==` ?

**Comment by ppp0** [comment]
good to know! @kris-lab pliiiiz

**Comment by njam** [comment]
Are you sure we should have all those sources in sources-vivid? Universe, Multiverse?
We recently removed backports for debian!

**Comment by njam** [comment]
(I would stick to the basics by default, and additional repos when needed. It makes things easier in the long run!)

**Comment by ppp0** [comment]
sgtm
@njam please review

**Comment by kris-lab** [comment]
afaics lgtm

**Comment by njam** [comment]
No specs did run? Do you know why? Can you investigate?

**Comment by njam** [comment]
And "puppet" is missing the adjustments in `operatingsystem_support`?

**Comment by ppp0** [comment]
From `ci`
```
Your bundle is complete!
It was installed into ./.bundle
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
==> Debian-7: Checking for updates to 'cargomedia/debian-7-amd64-default'
    Debian-7: Latest installed version: 0.18.0
    Debian-7: Version constraints: 
    Debian-7: Provider: virtualbox
==> Debian-7: Box 'cargomedia/debian-7-amd64-default' (v0.18.0) is running the latest version.
==> Ubuntu-1504: Checking for updates to 'cargomedia/ubuntu-1504-default'
    Ubuntu-1504: Latest installed version: 0.6.0
    Ubuntu-1504: Version constraints: 
    Ubuntu-1504: Provider: virtualbox
==> Ubuntu-1504: Box 'cargomedia/ubuntu-1504-default' (v0.6.0) is running the latest version.
vagrant halt --force
==> Ubuntu-1504: VM not created. Moving on...
Finished: SUCCESS
```

**Comment by ppp0** [comment]
@njam: puppet is missing the `operatingsystem` clause because its specs are not yet tested (ready?) for vivid

**Comment by njam** [comment]
Makes sense! (didn't think about puppet master…)

Do you know why the tests didn't run?

**Comment by njam** [comment]
Looks to me like the `cleanup` rake task kicked in.

**Pull request merged**
