### PR TITLE
Add critical_unit for each non-daemon monit-entry

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by njam** [comment]
Remove `require 'monit'` from some specs

**Comment by kris-lab** [comment]
Let's wait with this PR for https://github.com/cargomedia/puppet-packages/pull/1524

Some changes introduced in this PR are also applied in https://github.com/cargomedia/puppet-packages/pull/1524

@tomaszdurka will let you know when this would be ready for merging upstream.

**Comment by ppp0** [comment]
- Remove `monit-alert` script completely
 - Remove usages in puppet-packages and pulsar-conf-cargomedia
 - Change alerting in copperegg to go off if monit entries are "not ok" for 10 mins

**Comment by tomaszdurka** [comment]
@ppp0 or @njam wanna review?

**Comment by ppp0** [comment]
I'm up to take care of https://github.com/cargomedia/puppet-packages/pull/1498#issuecomment-251132691 in a follow-up ticket

**Comment by njam** [comment]
agreed

**Comment by tomaszdurka** [comment]
@ppp0 please confirm

**Pull request merged**
