### PR TITLE
Add metadata and puppetfile to Nvidia module

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look

**Comment by njam** [comment]
Should in require bipbip

**Comment by kris-lab** [comment]
I was thinking as well:) Should we require virtual resources in puppetfile? I added this to be on safe site!

**Comment by njam** [comment]
Yes it's needed, otherwise puppet will not know the resource.

**Comment by kris-lab** [comment]
Funny, because I have applied this without `metdata` and `puppetfile` using `puppet agent -t` and it worked.

**Comment by njam** [comment]
Yeah on production it usually works, because some other module already requires bipbip, so it's on the path?

**Comment by kris-lab** [comment]
agree

**Pull request merged**
