### PR TITLE
Adjust cm-janus error log monitoring to new log4js logger

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
I understand a match looks like this:
```
2016-01-21 17:24:31.277 ERROR - <message>
```

The reason to match everything *before* "ERROR" is to not have false positives? In that case I think we should make sure that we match the beginning of the line as well?
So rather `'^[\d\-\:\s\.]+ERROR'`?

You can test it btw with:
```
irb
> '2016-01-21 17:24:31.277 ERROR - Error: Command failed:'.match(/^[\d\-\:\s\.]+ERROR/)
```

**Comment by vogdb** [comment]
Good catch!

**Comment by vogdb** [comment]
I tested on this
screen shot 2016-01-22 at 18 48 13

@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
