### PR TITLE
Add Jessie to missing modules for ci deployment

### PR DESCRIPTION
**Pull request by ppp0**
Still to be done: - for https://github.com/cargomedia/puppet-cargomedia/issues/1034

- [x] copperegg_revealcloud
- [x] network
- [x] augeas
- [x] sysctl
- [x] iptables

Other forgotten (and needed) modules:
- [x] vagrant (solved in #1153)
- [x] virtualbox
- [x] raid
- [x] gearman (~~#1167~~ #1172)

### CODE REVIEW

**Comment by ppp0** [comment]
solved in #1135

**Comment by ppp0** [comment]
Found more missing specs

**Comment by ppp0** [comment]
`php5` module (`php5::extension::gearman`) has a dependency towards `libgearman-dev`.. waiting for https://github.com/cargomedia/debian-packages/issues/95

**Comment by ppp0** [comment]
composer and php5 being taken care of in #1165

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
I will let Jenkins decide.

**Comment by ppp0** [comment]
screen shot 2016-02-11 at 11 01 57
Our incorruptible arbiter

**Comment by ppp0** [comment]
Turns out apache2 is not trivial. Jessie has apache 2.4 vs apache 2.2 on wheezy. Meaning at least this: https://httpd.apache.org/docs/2.4/upgrading.html

As discussed: drop Apache2 support for Jessie (need to [migrate revive to nginx  #1166](https://github.com/cargomedia/puppet-packages/issues/1166))

**Comment by ppp0** [comment]
Waiting for #1167 (gearman spec failing)

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
@njam please review this humble PR (I took liberty not to revert the `ssl.conf` for apache2 as this will harden it and we'll soon phase it out)

**Comment by njam** [comment]
What's the reasoning for this apache change? I'm not sure it's a good idea to change something on its config, if there's even a slight chance that it will have an undesired effect. Especially if we're going to replace it soon.

**Comment by ppp0** [comment]
ok, virtualbox is the left over from a long journey

@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
