### PR TITLE
Pass "passphrase" to ssh-keygen, make command execution more robust

### PR DESCRIPTION
**Pull request by njam**
Puh this took me a long time to debug. `ssh-keygen` was asking for a passphrase on the terminal (within passenger), and everything got stuck indefinitely as a result.
@tomaszdurka @ppp0 @kris-lab please review

### CODE REVIEW

**Comment by tomaszdurka** [comment]
From issue description I understood you will pass passphrase. Am I missing place where you are passing it?

Agree with exception catching and improving its message.

**Comment by njam** [comment]
I'm passing `-N ''` - so empty passphrase, so that the program doesn't ask for one on the terminal!

**Comment by njam** [comment]
Manpage:
```
     ssh-keygen [-q] [-b bits] -t type [-N new_passphrase] [-C comment]
                [-f output_keyfile]
```

agree?

**Comment by kris-lab** [comment]
lgtm

**Comment by tomaszdurka** [comment]
Ah, I was looking for `-P`, but this is for old passphrase... good for me.

**Comment by ppp0** [comment]
Uh, good catch

**Pull request merged**
