### PR TITLE
socket-redis for jessie

### PR DESCRIPTION
**Pull request by ppp0**
depends on #1258, #1256 
part of  #1254

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- How about removing SSL support? It's not a use case, and anyway better and easier to put nginx in front.
- Daemon: require logdir
- Logdir: requiring user not needed (happens automatically)

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- /etc/socket-redis: Not needed?

rest lgtm

**Comment by njam** [comment]
@ppp0 wanna finish this up?

**Comment by ppp0** [comment]
The build failure is misleading. Only tearing down the test environment had issues (see https://github.com/cargomedia/puppet-packages/issues/1348)

**Pull request merged**
