### PR TITLE
Remove bipbip::plugin::cm from bipbip module

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/puppet-cargomedia/pull/704

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review; Do you agree to remove bipbip-cm repo as well? I mean first from rubygem then github? I am not sure if I have access for that.

**Comment by njam** [comment]
Agree.
Can you try removing them and let me know if you need help?

**Comment by kris-lab** [comment]
- `cargomedia/bipbip-cm` repo has been removed
- `bipbip-sm@0.1.0` has beed yank! There is still reference on rubygems. Can not see any option to remove it completely. Do you?

**Comment by njam** [comment]
Nope I think the idea is that you just make it unavailable.

Also:
> Once you've yanked all versions of a gem, anyone can push onto that same gem namespace and effectively take it over. 

http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem

**Comment by kris-lab** [comment]
:+1:

**Pull request merged**
