### PR TITLE
Spec testing infrastructure for Jessie

### PR DESCRIPTION
**Pull request by ppp0**
* Depends on https://github.com/cargomedia/vagrant-boxes/issues/61
* Vagrantfile
* spec_helper check if adaptations needed
* some basic spec test runs to check if ok

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review - tests pass locally! should on ci, too (apt-get cache manually invalidated there on both ci2 and ci3)

**Comment by ppp0** [comment]
grr errors on ci2
```

      Command: ["import", "/var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "debian-8-amd64-default_1453993273112_83148", "--vsys", "0", "--unit", "7", "--disk", "/var/lib/jenkins/VirtualBox VMs/debian-8-amd64-default_1453993273112_83148/debian-8-amd64-default-disk1.vmdk"]
      
      Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
      Interpreting /var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/box.ovf...
      OK.
      0%...10%...20%...30%...40%...50%...
      Progress state: VBOX_E_FILE_ERROR
      VBoxManage: error: Appliance import failed
      VBoxManage: error: Could not create the imported medium '/var/lib/jenkins/VirtualBox VMs/debian-8-amd64-default_1453993273112_83148/debian-8-amd64-default-disk1.vmdk'.
      VBoxManage: error: VMDK: Compressed image is corrupted '/var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/debian-8-amd64-default-disk1.vmdk' (VERR_ZIP_CORRUPTED)
      VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
      VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 877 of file VBoxManageAppliance.cpp
      
    daemon Service "my-program" 
    RuntimeError:
      Command execution failed:
      vagrant up --no-provision Debian-8
      Bringing machine 'Debian-8' up with 'virtualbox' provider...
      ==> Debian-8: Importing base box 'cargomedia/debian-8-amd64-default'...
      
Progress: 20%
Progress: 30%
Progress: 40%
Progress: 50%There was an error while executing `VBoxManage`, a CLI used by Vagrant
      for controlling VirtualBox. The command and stderr is shown below.
      
      Command: ["import", "/var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "debian-8-amd64-default_1453993273112_83148", "--vsys", "0", "--unit", "7", "--disk", "/var/lib/jenkins/VirtualBox VMs/debian-8-amd64-default_1453993273112_83148/debian-8-amd64-default-disk1.vmdk"]
      
      Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
      Interpreting /var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/box.ovf...
      OK.
      0%...10%...20%...30%...40%...50%...
      Progress state: VBOX_E_FILE_ERROR
      VBoxManage: error: Appliance import failed
      VBoxManage: error: Could not create the imported medium '/var/lib/jenkins/VirtualBox VMs/debian-8-amd64-default_1453993273112_83148/debian-8-amd64-default-disk1.vmdk'.
      VBoxManage: error: VMDK: Compressed image is corrupted '/var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/debian-8-amd64-default-disk1.vmdk' (VERR_ZIP_CORRUPTED)
      VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
      VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 877 of file VBoxManageAppliance.cpp
      
    daemon Command "monit summary | grep -E 'Pro.+my-program.+[Running|ok]'" exit_status 
    RuntimeError:
      Command execution failed:
      vagrant up --no-provision Debian-8
      Bringing machine 'Debian-8' up with 'virtualbox' provider...
      ==> Debian-8: Importing base box 'cargomedia/debian-8-amd64-default'...
      
Progress: 20%
Progress: 30%
Progress: 40%
Progress: 50%There was an error while executing `VBoxManage`, a CLI used by Vagrant
      for controlling VirtualBox. The command and stderr is shown below.
      
      Command: ["import", "/var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "debian-8-amd64-default_1453993273112_83148", "--vsys", "0", "--unit", "7", "--disk", "/var/lib/jenkins/VirtualBox VMs/debian-8-amd64-default_1453993273112_83148/debian-8-amd64-default-disk1.vmdk"]
      
      Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
      Interpreting /var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/box.ovf...
      OK.
      0%...10%...20%...30%...40%...50%...
      Progress state: VBOX_E_FILE_ERROR
      VBoxManage: error: Appliance import failed
      VBoxManage: error: Could not create the imported medium '/var/lib/jenkins/VirtualBox VMs/debian-8-amd64-default_1453993273112_83148/debian-8-amd64-default-disk1.vmdk'.
      VBoxManage: error: VMDK: Compressed image is corrupted '/var/lib/jenkins/.vagrant.d/boxes/cargomedia-VAGRANTSLASH-debian-8-amd64-default/0.1.0/virtualbox/debian-8-amd64-default-disk1.vmdk' (VERR_ZIP_CORRUPTED)
      VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
      VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 877 of file VBoxManageAppliance.cpp
      
```

investigating

**Comment by njam** [comment]
- Vagrantfile: why change IP address of the existing box? I suggest to keep it, to avoid problems?

rest lgtm!

btw I would suggest to streamline json to `"operatingsystemrelease": ["7", "8"]`, wdyt?

**Comment by ppp0** [comment]
* agree: what is causing problems is changing the forwarded port, but ip address is bound for trouble, too
* streamline, it's my code styler that does messy things - will revert by hand :(

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
>Finished in 1 hr 40 mins 48 secs.
Success! 112 specs run, 0 failures (469 examples, 0 failures)

vagrant halt --force
==> Debian-8: Forcing shutdown of VM...
==> Ubuntu-15.04: Forcing shutdown of VM...
==> Debian-7: Forcing shutdown of VM...
Finished: SUCCESS


@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
