### PR TITLE
remove svm module

### PR DESCRIPTION
**Pull request by alexispeter**
See https://github.com/cargomedia/cm/issues/2525

### CODE REVIEW

**Comment by alexispeter** [comment]
please review @kris-lab

**Comment by njam** [comment]
I think there's a usage in the "cm" module. Could you grep in the whole project?

**Comment by alexispeter** [comment]
please review @njam

**Comment by njam** [comment]
lgtm

We should probably wait to merge it until the change is released. At least until the job maintenance-local is not running anymore - then the extension should not be used anymore.

**Comment by alexispeter** [comment]
should be ready to merge @njam

**Comment by njam** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Pull request merged**
