### PR TITLE
Create module for loggly-github

### PR DESCRIPTION
**Pull request by njam**
https://github.com/cargomedia/loggly-github

Depends on https://github.com/cargomedia/puppet-packages/issues/1261

### CODE REVIEW

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
@ppp0 @kris-lab please review

**Comment by ppp0** [comment]
nice tool :)

lgtm

**Pull request merged**
