### PR TITLE
Add module to blacklist kernel modules

### PR DESCRIPTION
**Pull request by njam**
Add a file to `/etc/modprobe.d/`, which contains 1 or more lines of:
```
blacklist <module name>
```

### CODE REVIEW

**Comment by njam** [comment]
@ppp0 @kris-lab please review

**Comment by ppp0** [comment]
I wonder if `modprobe` shouldn't be refreshed/called? Or name the define `modprobe_conf` ?

**Comment by kris-lab** [comment]
Looks good. 

In general to apply it fully you should reboot system? Otherwise you have to make sure the specific module is loaded or unloaded from kernel with `modprobe module-name` or `modprobe -r module-name`?

**Comment by njam** [comment]
Ok agree, please review!

**Comment by kris-lab** [comment]
afaics lgtm

**Comment by njam** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
>In general to apply it fully you should reboot system? 

I'm not completely sure on this one - but surely, it gives you a clean, defined state. To me, `modprobe` sounds like the util bin loading the module whereas here we manipulate its config

but be it, lgtm

**Comment by njam** [comment]
Afaik "udev" uses "modprobe" to load modules when devices are attached. Now I'm unloading a module if it's loaded when we blacklist it. So it should be in the desired state.

**Pull request merged**
