### PR TITLE
Fix failing db backup script

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
in general looks good. What about `critical-units.target` instead of monit, will it alert?

**Comment by ppp0** [comment]
It will, after 10min. But the critical operation is expected to last less. Critical is when we stop the mysql server on db9 to copy it's /var/lib to a temp directory. This takes some minutes due to its size. After that, we restart and the critical period is over. Of course, the backup proper afterwards takes hours to complete

**Comment by ppp0** [comment]
But I get you: shall we implement some silencing of `critical-units.target` ?

**Comment by kris-lab** [comment]
Let's keep it like is now. If this 10min is too less, then let's find better solution. Agree?

**Comment by ppp0** [comment]
fully agree

**Pull request merged**
