### PR TITLE
Create systemd critical unit for cm applications

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@kris-lab please review
@njam fui

**Comment by kris-lab** [comment]
- modules/cm/manifests/application.pp - WARNING: top-scope variable being used without an explicit namespace on line 37
- modules/cm/manifests/application.pp - WARNING: double quoted string containing no variables on line 39
- remove empty line

**Comment by tomaszdurka** [comment]
@kris-lab can you check?

There is one failing test related to nodejs installation problem - it's one timer, so let's not waste ci's power and ignore it.

**Comment by kris-lab** [comment]
Looks good in general. Could you link on what it depends on?

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
Depends on #1483

**Comment by tomaszdurka** [comment]
@kris-lab please review

**Comment by tomaszdurka** [comment]
@njam you can take a look too!

Not sure about the systemd::group... used it in two places and didn't like directory creation in cm::application. Or maybe this directory should be done by pulsar?

**Comment by njam** [comment]
- systemd::group: call it `systemd::target`?

**Comment by kris-lab** [comment]
Could you please merge upstream?

**Comment by tomaszdurka** [comment]
Pulled, but can't push... github!

**Comment by tomaszdurka** [comment]
Done!

**Comment by njam** [comment]
- Call it `systemd::target` and `systemd::service` and omit the file extension from the name

**Comment by tomaszdurka** [comment]
Oh this CI :o

**Comment by tomaszdurka** [comment]
Relief!
image

@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
