### PR TITLE
Migrate revive to nginx

### PR DESCRIPTION
**Pull request by ppp0**
To drop apache2 as a dependency, let's do the move.

see
https://gist.github.com/metafour/a69d7c67724a0523d6f9
https://www.digitalocean.com/community/tutorials/how-to-install-openx-on-centos-6

### CODE REVIEW

**Comment by ppp0** [comment]
next step: migrate to jessie

**Comment by ppp0** [comment]
phase out `php5::extension::apc` (in favour of apcu and opcache)

**Comment by ppp0** [comment]
@njam please review

**Comment by ppp0** [comment]
This will need some luv when merging. Likely, apache needs to be stopped and uninstalled first

**Comment by njam** [comment]
- manifests/init.pp: This `expires 1y` looks weird - this will apply to any request I guess? We didn't have it in apache, and I think it's something the application (revive) should decide about for reach request?
- manifests/init.pp: Where is this gzip mimetype list coming from? Is it good to zip PNGs?

**Comment by ppp0** [comment]
* Removed
* the list's original is here: https://github.com/cargomedia/puppet-packages/blob/master/modules/cm/manifests/vhost.pp#L113 - I thought it to be good but it can be removed, also, a `gzip_min_length` could be defined. I'd say gzipping statics is good practice?

**Comment by ppp0** [comment]
@njam please another look

**Comment by njam** [comment]
Images like PNG are usually already compressed, so I think it's not common to zip them again (little to no gain). I would suggest to stick to the original list, as here: https://github.com/cargomedia/puppet-packages/blob/master/modules/cm/manifests/vhost.pp#L113

Otherwise lgtm

**Comment by ppp0** [comment]
retest this please

**Pull request merged**
