### PR TITLE
Replace httpredir as repo source

### PR DESCRIPTION
**Pull request by ppp0**
Using [httpredirector](https://github.com/rgeissert/http-redirector) as deb repo source as we do makes caching very hard if not impossible (see [caching issues](https://github.com/rgeissert/http-redirector/search?q=cache&type=Issues&utf8=%E2%9C%93) )

We want to populate the cache with predictable urls - otherwise its usefulness will be impaired

### CODE REVIEW

**Comment by ppp0** [comment]
This will only apply if `facter` states that the virtualization being run on is "virtualbox" - so it should not affect production (unless we run virtualboxes in production)

@kris-lab please review

**Comment by kris-lab** [comment]
As discussed it looks good.

**Comment by kris-lab** [comment]
But lets fix this as well ` apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886`

**Comment by ppp0** [comment]
Yes, this was due to a restrictive acl (fixed in #1558 )

**Pull request merged**
