### PR TITLE
Drop unused /etc/aliases to manage email forwards in postfix

### PR DESCRIPTION
**Pull request by ppp0**
Via https://github.com/cargomedia/puppet-packages/pull/1167
E.g. with:
```
bundle exec rake spec:cron os=Debian-7 keep_box=true
```

Before:
```
vagrant@debian-7-amd64-default:~$ cat /etc/aliases
postmaster: root
monit: root
```
After:
```
vagrant@debian-7-amd64-default:~$ cat /etc/aliases
postmaster: root
```

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
Is there any mail sent to "postmaster"? If so we should probably add this forward?

**Comment by ppp0** [comment]
Seem these entries need to be there in order to comply with RFC 5321 (see https://tools.ietf.org/html/rfc2142#section-5). I'm not sure shall we put them statically into the template (as per this PR), configure it in https://github.com/cargomedia/puppet-cargomedia/blob/master/modules/cargomedia/files/hiera-data/defaults.json#L25 or another option

@njam wdyt?

**Comment by njam** [comment]
lgtm as you did it

**Pull request merged**
