### PR TITLE
Cm_janus module

### PR DESCRIPTION
**Pull request by ppp0**
Install https://github.com/cargomedia/cm-janus with nginx in front of it! Should be similar to socket-redis.

### CODE REVIEW

**Comment by ppp0** [comment]
@tomaszdurka as announced, `cm-janus` refuses to start at this point

**Comment by tomaszdurka** [comment]
Please add `gpp` as dependency for inotify npm.

**Comment by ppp0** [comment]
depends on #989 (unverified)

**Comment by ppp0** [comment]
depends on #992

**Comment by ppp0** [comment]
Waiting for https://github.com/cargomedia/cm-janus/issues/48

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
As we discussed on call, let's finish specs first!

**Comment by ppp0** [comment]
OK this finally should work as expected. @kris-lab please review

**Comment by kris-lab** [comment]
Yep, agree, looks good!

**Pull request merged**
