### PR TITLE
[Jessie] - Migration of composer and php5

### PR DESCRIPTION
**Pull request by ppp0**
Follow-up of https://github.com/cargomedia/puppet-packages/pull/1150
Needs #1164 https://github.com/cargomedia/puppet-packages/issues/1168

Make following modules run on Jessie:
- [x] composer
- [x] php5

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

we're not using suhosin, are we?

**Comment by njam** [comment]
Agree! Then we can probably also drop it for wheezy and remove it completely?

**Comment by ppp0** [comment]
@njam  please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
