### PR TITLE
Implement janus-cluster member - register end-point

### PR DESCRIPTION
**Pull request by tomaszdurka**
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1274

Not fully standard to https://github.com/cargomedia/janus-cluster

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@kris-lab wanna review?

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
@cargomedia/devops can anyone tell me why I am getting this error about invalid variable for `JSON.generate`? This runs correct on my local environment. 

Is puppet on CI somehow different than our local ones and possibly passes variables to templates in different way?

Thanks.

**Comment by njam** [comment]
Should not, those commands run with `bundle exec` and the `Gemfile.lock` is committed!
I can reproduce locally:
```sh
$ bundle exec rake syntax
---> syntax:manifests
---> syntax:templates
rake aborted!
JSON::GeneratorError: only generation of JSON objects or arrays allowed
/Users/reto/Projects/puppet-packages/.bundle/vendor/ruby/2.1.0/gems/json_pure-1.8.3/lib/json/common.rb:223:in `generate'
/Users/reto/Projects/puppet-packages/.bundle/vendor/ruby/2.1.0/gems/json_pure-1.8.3/lib/json/common.rb:223:in `generate'
modules/janus_cluster/templates/register_member.sh.erb:6:in `<main>'
/Users/reto/Projects/puppet-packages/.bundle/vendor/ruby/2.1.0/gems/puppet-syntax-1.4.1/lib/puppet-syntax/templates.rb:17:in `block in check'
/Users/reto/Projects/puppet-packages/.bundle/vendor/ruby/2.1.0/gems/puppet-syntax-1.4.1/lib/puppet-syntax/templates.rb:13:in `check'
/Users/reto/Projects/puppet-packages/.bundle/vendor/ruby/2.1.0/gems/puppet-syntax-1.4.1/lib/puppet-syntax/tasks/puppet-syntax.rb:51:in `block (2 levels) in initialize'
Tasks: TOP => syntax => syntax:templates
(See full trace by running task with --trace)
```

Are you sure you're using the correct bundler environment? Maybe run `bundle install`?

**Comment by kris-lab** [comment]
- mode: maybe `755` => `0755 `?
- unify naming: `webSocketAddress` => `websocket_address `?

As we discussed I am not sure about name `janus_cluster::member` - this logic sounds more like helper registration or similar. Maybe "member_helper" makes more sense? However I am not sure if we extend this resource in the future. @tomaszdurka wdyt?

**Comment by tomaszdurka** [comment]
Maybe we should reconsider naming and modules in general.

You probably want to name this helper, as you don't see this small module as "janus_cluster::member", but just addition. That's probably my bad as of naming `janus-cluster` this way. `janus-cluster` should be used rather as concept not single piece of software. Originally nodejs app was called `janus-cluster-manager` which probably is better. Than currently implemented module would be called `janus-cluster-manager::member/subscriber` which makes more sense. 

Possibly we could add a wrapper class for what we try to add withing `janus::role::cluster...` and instead have it within `janus_cluster::member` or even `janus_streaming_cluster::member`.

**Comment by kris-lab** [comment]
closing in favor of https://github.com/cargomedia/puppet-packages/pull/1204

**Pull request closed without merging**
