### PR TITLE
mysqlproxy for Jessie

### PR DESCRIPTION
**Pull request by ppp0**
It depends on #1243 changes...

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review (#1243 to be merged with master and later master pulled here first)

**Comment by kris-lab** [comment]
ok, let's review and merge stuff one-by-one. The code with all this pulls is kind of unreadable.

**Comment by ppp0** [comment]
I'm very sorry. The only commit which is relevant to this PR is https://github.com/cargomedia/puppet-packages/pull/1425/commits/7fac6636e1b733ec2386dc3d45d94e34079f92a0

**Comment by ppp0** [comment]
The dependency (#1243) is really **only for the spec tests* to succeed

**Comment by kris-lab** [comment]
@ppp0 taking over from here

**Comment by kris-lab** [comment]
@njam wanna have a look?

**Comment by njam** [comment]
- mysql_proxy/manifests/init.pp: I would in general try to avoid using `->` and `~>`, because it's much easier to refactor code that uses `require`/`notify` etc (except maybe for tests), wdyt?
- mysql_proxy/spec/init/spec.rb: Monit check can be removed here, since this is now handled by the "daemon" module, which has tests for it. We check that the port is listening, which should be enough here.

**Comment by kris-lab** [comment]
@njam please re-review

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
Deployment will affect `www[3,4,5]`, `search2` and `janus[2,4,5]`. Some cleanup might be required.

**Pull request merged**
