### PR TITLE
Add bipbip log_parser for systemd

### PR DESCRIPTION
**Pull request by tomaszdurka**
After https://github.com/cargomedia/puppet-packages/pull/1027

Look for undesired restarts of daemons in the systemd log?
This could replace monit completely!

@tomaszdurka wanna look into this?
cc @kris-lab @ppp0

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Oh, didn't make pull-request out of it.

@ppp0 please review

**Comment by ppp0** [comment]
sorry I'm stuck on http://blog.delouw.ch/2013/07/24/why-journalctl-is-cool-and-syslog-will-survive-for-another-decade/

I reckon, we'll keep syslog.. But somehow if feels redundant on systemd/journalctl based distros

In that case, lgtm

**Comment by ppp0** [comment]
Another interesting piece ([systemd for sysadmins, vol. 17](http://0pointer.de/blog/projects/journalctl.html)) :cold_sweat:

**Comment by tomaszdurka** [comment]
Shall we add `journal` bipbip plugin?

**Comment by njam** [comment]
@tomaszdurka what is the status of this one? does it work - ready to merge?

**Comment by ppp0** [comment]
@tomaszdurka No, for the time being no `journalctl`!  Since all it's output gets dumped to `syslog` I would stick with it! There's more issues to come otw with journal persistance et al. I think it can be merged?

**Comment by ppp0** [comment]
@njam to me it looks like it can be merged

**Comment by njam** [comment]
@tomaszdurka can you confirm?

**Pull request merged**
