### PR TITLE
Use daemon for cm_janus

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@dergraf @ppp0 please review.

As mentioned to Andre I had problems keeping user as `cm-janus:cm-janus`.
To reproduce change user to `cm-janus:cm-janus`.
Strange as according to `/etc/passwd`, `/etc/group` files user and group are present. 
When running daemon with `cm-janus` only it works and in the end it works the same way (takes `cm-janus` as group).

Questions:
- is `user:group` pair working for systemd?
- is there something off with our daemon init script? - it worked with previous script

**Comment by dergraf** [comment]
@ppp0 any ideas regarding this?

**Comment by ppp0** [comment]
Interesting..

I agree that `.conf` files belonging to the same user/group of the process needing them looks kinda good, but I also agree, that this was not the case before. `.conf` files where happily owned by root.

**Comment by tomaszdurka** [comment]
Indeed. Conf files didn't need to be changed. There was problem with log-dir. Could not start it as `cm-janus` user without setting it as owner of the log-dir.

**Comment by ppp0** [comment]
I'm also experiencing issues with logging (see https://github.com/cargomedia/puppet-packages/blob/master/modules/janus/templates/init.sh#L31 - old school redirection to a log file). In systemd this is no problem as logging come included (`journalctl -u janus` e.g.)

**Comment by njam** [comment]
- manifests/init.pp: I think config files should be owned by `root` (security considerations)
- manifests/init.pp: Daemon should require config file
- init.sh: delete

Otherwise this looks good, and could be merged?

**Comment by tomaszdurka** [comment]
@njam please confirm

**Comment by njam** [comment]
lgtm

**Pull request merged**
