### PR TITLE
Update mms monitoring agent

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
looks good, backup agent is not updated?

**Comment by ppp0** [comment]
As I gather from https://mms.mongodb.com/settings/agents/53a29fcfc84d93219d181511 the backup agent is still up-to-date

**Comment by ppp0** [comment]
applying puppet to make sure agent is updated everywhere applicable

**Pull request merged**
