### PR TITLE
Add systemd_unit bipbip for critical_units

### PR DESCRIPTION
**Pull request by tomaszdurka**
Depends on https://github.com/cargomedia/bipbip/pull/158

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@kris-lab wanna review?

**Comment by njam** [comment]
Shouldn't the "metric_group" be something like "systemd-critical" or "critical-units"?

Otherwise lgtm

**Comment by tomaszdurka** [comment]
It's "critical-units" now.

**Comment by njam** [comment]
lgtm

**Pull request merged**
