### PR TITLE
Add git::repository resource

### PR DESCRIPTION
**Pull request by njam**
@tomaszdurka please review

A resource to create a checkout of a git repo at a specific tag.
Can be used for cm-janus modules (#999)

cc @ppp0

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Mixed feelings about name. Maybe `git::repo(sitory)`? I believe you have thought about it. On the other hand the way you've put this in description makes sense.
Isn't this a git repo with specific "ref state"?

Btw you are testing files and their contents. Have you thought about using git commands rather than this?

**Comment by njam** [comment]
I like `git::repository($remote)`.

I thought about using git commands in the specs. But it will end up being almost the same as in the manifest, which might be a bit risky, if there's a bug…

@tomaszdurka wdyt?

**Comment by njam** [comment]
@ppp0 please review

**Comment by tomaszdurka** [comment]
Looks good. Maybe I would rather use `ref` instead of `version`?

**Comment by njam** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Looks good.

**Pull request merged**
