### PR TITLE
Network for Ubuntu

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
I decided to keep `notify  => Exec['hostname.sh']` instead of doing `subscribe=>File['/etc/hostname']` on both `Exec` resources and introduce `hostname` and `hostname.sh` name.

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
Rename exec from `hostname.sh` to just `apply hostname`?

**Comment by kris-lab** [comment]
@njam please review

**Pull request merged**
