### PR TITLE
Revert "[Temp Workaround] - Use http instead of https for nodejs"

### PR DESCRIPTION
**Pull request by kris-lab**
Reverts cargomedia/puppet-packages#1570

### CODE REVIEW

**Comment by kris-lab** [comment]
@ppp0 for tracking

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
Starting with [this comment](https://github.com/nodesource/distributions/issues/388#issuecomment-260984736) it looks like Amazon rolled out a fix

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
