### PR TITLE
Catch TrasportException in Satis Daemon

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
ok, makes sense. Wouldn't it better to use TRAP as cleanup e.g. send e-mail (instead of system-cat as discussed [here](https://github.com/cargomedia/puppet-cargomedia/issues/1580))

**Comment by ppp0** [comment]
Good idea!

**Comment by ppp0** [comment]
@kris-lab please enjoy

**Comment by ppp0** [comment]
Again these build failures:
```
[..]
Error: /Stage[main]/Satis/Composer::Project[composer/satis]/Exec[install composer/satis]/returns: change from notrun to 0 failed: Command exceeded timeout
[..]
```
:zipper_mouth_face:

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
I'll leave this to @kris-lab to verify

**Comment by kris-lab** [comment]
look good to me

**Pull request merged**
