### PR TITLE
Optionally prevent autostart of daemons at creation time

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab kindly review, please

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- Instead of introducing a new variable `$unless_start_on_create` could we just use `! $start_on_create`?
```sh
$ sh -c '(! false) && echo jo'
jo
```

**Comment by ppp0** [comment]
It's true, but otoh
* the variable introduced is local, the resulting code is still far from unreadeable?
* It's a way of *sanitise* the input.. One could pass other values than a boolean and have them executed.

I know it's an abstract use case but it's going against some security basics

**Comment by njam** [comment]
I found it rather a bit confusing with an inverse variable of the input, and the comment explaining the logic. Having a *logical not* operator would be more understandable to me.
But it's fine like this too.
lgtm

**Pull request merged**
