### PR TITLE
Fix version check for ffmpeg 2.6

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@kris-lab please review

**Comment by njam** [comment]
lgtm, I trust you tested this

**Comment by tomaszdurka** [comment]
That is current version line:
```
ffmpeg version 2.6 Copyright (c) 2000-2015 the FFmpeg developers
```

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
