### PR TITLE
Introduce module locale

### PR DESCRIPTION
**Pull request by ppp0**
To streamline `/etc/default/locale` everywhere.

Solves https://github.com/cargomedia/puppet-cargomedia/issues/1256

### CODE REVIEW

**Comment by ppp0** [comment]
TL;DR

* Jessie/Ubuntu: `localectl` manipulates `/etc/default/locale` when modifying the locale
* Done some testing on `puppet1` (Jessie on Hetzner). When I finally set `LANG="en_US.UTF-8"` as everywhere on our vagrant boxes, the UTF-8 char `…` became accessible vie keyboard
* No changes expected otherwise as we've been observing divergence on Hetzner/Jessie only
* May be Softlayer/Jessie will benefit from this, too


Either way, this should make Jenkins output readable again!

@kris-lab please review

**Comment by kris-lab** [comment]
Should LANG be configurable on the `class locale {}` level? I would vote to do it.

**Comment by ppp0** [comment]
@kris-lab Proszę :)

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
