### PR TITLE
Use composer::project for satis installation

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by tomaszdurka** [comment]
Only https://github.com/tomaszdurka/puppet-packages/commit/ee49338242fbb8929f369fcec93d198146cc047e needs review - rest is formatting, folder renaming.

**Comment by njam** [comment]
retest this please
(checking jenkins)

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
Please merge upstream

**Comment by tomaszdurka** [comment]
Sorry thought I've already merged that - had conclicts and somehow postponed it.

@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
