### PR TITLE
Add private cargomedia source

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
Grrr...

specs fail with
```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: Failed to fetch https://debian-packages-private.cargomedia.ch/ZijJtxgkSLjE5jzDG8KO7W9ljVxBrjr/dists/vivid/main/binary-amd64/Packages  SSL: certificate subject name (*.cloudfront.net) does not match target host name 'debian-packages-private.cargomedia.ch'```

**Comment by ppp0** [comment]
@cargomedia/devops @dergraf  important

We'll need to change our URL.. this repo is public. Big sorry about this mistake

**Comment by tomaszdurka** [comment]
@ppp0 can you wipe your commit?

**Comment by ppp0** [comment]
Solved in https://github.com/cargomedia/puppet-cargomedia/pull/969

**Pull request closed without merging**
