### PR TITLE
Adapt server for mms agent downloads

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by njam** [comment]
Why does it fail on production but not in tests?

**Comment by ppp0** [comment]
Checking...

**Comment by ppp0** [comment]
Somehow the installer now expects user input to confirm overwriting the existing config file. Adding `--force-confold`

@tomaszdurka could you please review this shortie?

**Comment by tomaszdurka** [comment]
looks ok

**Pull request merged**
