### PR TITLE
Add bipbip logparser for cm-janus job failed

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Multiline doesn't matter in the end, as we just want the occurrences of specific text-blocks.
@njam please review/reply to general error monitoring

**Comment by njam** [comment]
- Let's define option `'metric_group' => 'cm-janus'` ?
 - Also add it for daemon? `'metric_group' => 'daemon'`
 - Check out the copperegg dashboard to see how it looks
- So "app error" will cover failing jobs?

**Comment by tomaszdurka** [comment]
It will cover all `error` in general. We decided to use `error` only for those errors which should not occur. If they occur it's mostly cause connected services "forced invalid state".

**Comment by tomaszdurka** [comment]
Or would you rather prefer to intercept invalid jobs errors separately?
I personally think having general error monitor is good. In perfect world we should never have those and if it happens it means there's "something" wrong and it requires investigation ;)

**Comment by njam** [comment]
sgtm, let's adjust the metric_group though

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by tomaszdurka** [comment]
Looks good.

**Pull request merged**
