### PR TITLE
Remove duplicate declaration from provision script (immediate solution)

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
Let's keep it but rename it, so we'll remember that we need to have `apt-get update` before provisioning

**Comment by njam** [comment]
ok… :D

**Comment by njam** [comment]
Killing jenkins build, because they use up all our workers.
I will merge this, let's wait for the nightly build!

**Pull request merged**
