### PR TITLE
Fix janus plugins config file name

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@ppp0 please review. current paths are incorrect

**Comment by ppp0** [comment]
I trust you to have checked that it works, lgtm

**Comment by kris-lab** [comment]
@ppp0 please have a look one more time. it works like that

**Comment by kris-lab** [comment]
@ppp0 according to the new config I have also added new switching-stream configuration see -> https://github.com/cargomedia/janus-gateway-rtpbroadcast/blob/master/conf/janus.plugin.cm.rtpbroadcast.cfg.sample#L6

**Comment by kris-lab** [comment]
merging

**Pull request merged**
