### PR TITLE
remove passing $ensure argument from all nginx::resources

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
resolves https://github.com/cargomedia/puppet-packages/issues/1649

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
Agree in general because we purge `conf.d`. We use atm:
```
    File["${nginx::params::nx_conf_dir}/conf.d"] {
      ignore  => 'vhost_autogen.conf',
      purge   => true,
      recurse => true,
    }
```

However we store partial file in `nginx.d` for concatenation in next step. Is it still properly working without setting `ensure => absent` for common resources (vhost, location, upstream)?

**Comment by ppp0** [comment]
* Where do we use `ensure => absent` to remove resources? 
* About purging. We could even get rid of this  `$nx_confd_purge` mechanism, as the default is true (makes sense to me) and we don't have cases where we would not purge the `conf.d` dir?
* Concatenation happens in a temp dir `${nginx::config::nx_temp_dir}/nginx.d` which is being populated in `nginx::service` 
```
  exec { 'rebuild-nginx-vhosts':
    command     => "/bin/cat ${nginx::params::nx_temp_dir}/nginx.d/* > ${nginx::params::nx_conf_dir}/conf.d/vhost_autogen.conf",
    refreshonly => true,
    unless      => "/usr/bin/test ! -f ${nginx::params::nx_temp_dir}/nginx.d/*",
    subscribe   => File["${nginx::params::nx_temp_dir}/nginx.d"],
  }
```

**Comment by kris-lab** [comment]
I haven't tested in person this new logic without param `ensure => [present/absent/file]` and with removed e.g.:
```
## Shared Variables
   $ensure_real = $ensure ? {
     'absent' => absent,
     default  => file,
   }
```
I was thinking that it could change the behaviour where incorrect temporary files from `nginx.d` could be concatenated into final `conf.d`.

If you tested all this cases then it looks good to me.

**Comment by ppp0** [comment]
retest this please

**Pull request merged**
