### PR TITLE
Use stdlib's "service_provider" fact

### LINKED ISSUE #1070: Puppet 3.8 doesn't work with systemd's "sysvinit compatibility layer"
Some of our services are using sysvinit-style scripts, which is supported by **systemd's sysvinit compatibility layer**. E.g. postfix, ntp, monit.

Unfortunately puppet's `Service` type only supports this scenario correctly in version 4 (see https://github.com/cargomedia/puppet-packages/pull/1068).

As an effect the `enabled?` check currently returns `false` although the service is enabled, and every puppet run will re-enable it.

cc @kris-lab @tomaszdurka @ppp0

### LINKED ISSUE #1071: Puppet 3.8 doesn't detect Service's "provider" correctly
For Ubuntu 15.04 detects either "sysvinit" or "upstart", but it should be "systemd".

Can be fixed by upgrading to Puppet 4.4: https://github.com/cargomedia/puppet-packages/pull/1068

Workarounds in place:
- puppet-packages: `site.pp` for "puppetmaster"
- sk: `bulldog.pp`

### PR DESCRIPTION
**Pull request by njam**
Closes #1071
Closes #1070

### CODE REVIEW

**Comment by njam** [comment]
@ppp0 @kris-lab please review

**Comment by njam** [comment]
@ppp0 @kris-lab please review

**Comment by kris-lab** [comment]
looks good

**Comment by ppp0** [comment]
this I call progress! nice!

**Pull request merged**
