### PR TITLE
Composer installer invoked at every puppet run

### PR DESCRIPTION
**Pull request by ppp0**
Since #1507 

Suspected error in `unless` clause

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab @njam please review

**Comment by ppp0** [comment]
tbh it is not clear to me why it failed before

```
root@debian-8-amd64-plain:/home/vagrant# composer --version | grep -w '1.2.1' ; echo $?
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.2.1 2016-09-12 11:27:19
0
root@debian-8-amd64-plain:/home/vagrant# composer --version --no-ansi| grep -w '1.2.1' ; echo $?
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.2.1 2016-09-12 11:27:19
0
root@debian-8-amd64-plain:/home/vagrant# man grep
root@debian-8-amd64-plain:/home/vagrant# composer --version --no-ansi| grep -e '1.2.1' ; echo $?
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.2.1 2016-09-12 11:27:19
0
root@debian-8-amd64-plain:/home/vagrant# composer --version --no-ansi| grep '1.2.1' ; echo $?
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.2.1 2016-09-12 11:27:19
0
```

all return 0

**Comment by ppp0** [comment]
Found the cause

```
Debug: Exec[curl /usr/local/lib/composer.phar](provider=posix): Executing check '/usr/local/bin/composer --version | grep -w '1.2.1''
Debug: Executing: '/usr/local/bin/composer --version | grep -w '1.2.1''
Debug: /Stage[main]/Composer/Exec[curl /usr/local/lib/composer.phar]/unless: 
Debug: /Stage[main]/Composer/Exec[curl /usr/local/lib/composer.phar]/unless:                                                                                             
Debug: /Stage[main]/Composer/Exec[curl /usr/local/lib/composer.phar]/unless:   [RuntimeException]                                                                        
Debug: /Stage[main]/Composer/Exec[curl /usr/local/lib/composer.phar]/unless:   The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  
Debug: /Stage[main]/Composer/Exec[curl /usr/local/lib/composer.phar]/unless:
```

Composer wants some (useful) environment vars to be set to tell us its version. A full path to the binary is not enough

**Comment by kris-lab** [comment]
Doesn't sounds serious `sweet_home`, but it's fine with me:)

**Comment by ppp0** [comment]
I can write something serious like `/` if you really want ;)

**Comment by njam** [comment]
> tbh it is not clear to me why it failed before

Why did you remove the `-w` then? Now it will also match `1.2.11`.

**Comment by ppp0** [comment]
true

**Comment by ppp0** [comment]
#1511

**Pull request merged**
