### PR TITLE
Chromium: remove build from source

### PR DESCRIPTION
**Pull request by ppp0**
Once we have Chrome@51 which is available in Ubuntu Wily https://github.com/cargomedia/puppet-cargomedia/issues/1350

### CODE REVIEW

**Comment by ppp0** [comment]
@njam done, please have a look

**Comment by njam** [comment]
@kris-lab could you review it?

**Comment by kris-lab** [comment]
For records, it reverts https://github.com/cargomedia/puppet-packages/pull/1388 and https://github.com/cargomedia/puppet-packages/pull/1396

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
