### PR TITLE
Apt transport https

### PR DESCRIPTION
**Pull request by ppp0**
Follow-up of https://github.com/cargomedia/puppet-packages/pull/989

### CODE REVIEW

**Comment by ppp0** [comment]
@njam you will not like it :)
@tomaszdurka you  probably won't either...

It's a way to break the dep cycle, though... Your thoughts please... I wouldn't spend too much time on this topic, if possible

**Comment by njam** [comment]
Could/should we ignore all resources that *start* with `apt`?

**Comment by ppp0** [comment]
Unfortunately, it does not sound like we could match substrings cf https://docs.puppetlabs.com/puppet/latest/reference/lang_collectors.html#equality-search...

`apt-transport-https` for a start?

**Comment by tomaszdurka** [comment]
Btw, is it ok to install `apt-transport-https` before first running usual `apt-update`?
Maybe it should even:
1. run `apt-update`
2. install `apt-transport-https`
3. run `apt-update`
4. install other packages

?

@ppp0 so `!~` cannot be used there?

**Comment by ppp0** [comment]
May be the first `apt-update` (which is being invoked in `provision.pp`) can be called as an exec? Right now, there is a `require 'apt::update'` which contains this `Exec -> Package` relationship. This `https` tranport is used for nodesource at the moment. I have seen it in another location in the wild as well. I imagine it will become more and more common with https becoming de-facto standard everywhere..

We actually could make it default in our vagrant-box (or even Preseed) and in pulsar-cargomedia's `install_basics` (https://github.com/cargomedia/pulsar-conf-cargomedia/blob/master/recipes/puppet/puppet.rb#L46)

I guess this would be the cleanest option? wdyt?

**Comment by ppp0** [comment]
This is super annoying: after merging, all nodes having a `nodejs` dependency fail with:
```
apt-get -y install  apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 109 kB of archives.
After this operation, 167 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  apt-transport-https
E: There are problems and -y was used without --force-yes
```

The solution, to save time, was: (done with `pulsar` everywhere)
```
monit stop puppet
rm -f /etc/apt/sources.list.d/nodesource.list 
apt-get update
apt-get -y install apt-transport-https
monit start puppet
```

Somehow, adding the `nodesource` list messes up with the apt keys.. See http://unix.stackexchange.com/questions/175764/untrusted-package-apt-transport-https and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=756614 (likely not fully related)

**Pull request merged**
