### PR TITLE
Backup copy network interface - To be able to revert

### PR DESCRIPTION
**Pull request by ppp0**
In case of mistakes in network config we would be able to revert by manually restoring the backup copy of `/etc/network/interfaces`

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review
@cargomedia/devops cc

**Comment by kris-lab** [comment]
agree, it is safe to have this feature.

lgtm

**Comment by ppp0** [comment]
@njam I let have you the last word ;)

**Comment by njam** [comment]
- Should make sure that this runs *before* we modify the original file
- The name is a bit unclear to me. Maybe just "interfaces.bak"?

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
Shouldn't this be one resource to require at the beginning of `network::interface` (instead of requiring it on every change)? Maybe a new `network::interfaces_backup`?

**Comment by ppp0** [comment]
agree much more elegant now. @njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
