### PR TITLE
Rework spec rake tasks to allow running on multiple os

### PR DESCRIPTION
**Pull request by tomaszdurka**
- Use custom Rake tasks (no rspec ones)
- Wrap functionality to find modules and specs (replace pattern with direct path to spec)
- Introduce SpecRunner to 
  - Allow run multiple specs on multiple os (gather results)
  - Allow running specific specs
  - Allow running specific os

### CODE REVIEW

**Comment by tomaszdurka** [comment]
TODO:
- return correct status for rake task
- add `operatingsystem_support` (almost done - not commited to make changes more clear)
- readd 'test:changes_from_branch' rake task

**Comment by tomaszdurka** [comment]
@njam @ppp0 feel free to review, comment, etc.

**Comment by tomaszdurka** [comment]
Retest this please.

**Comment by njam** [comment]
Great stuff!

- ./ruby/puppet_modules: should this directory be merged with `./spec/lib`?
- operatingsystem_support.json / map_os_to_box: How about we derive the box name from metadata.json's `operatingsystem` and `operatingsystemrelease` (`Debian-7`)? Then we can drop this file and let vagrant fail if there's no such box…
- ssl/spec.rb: revert formatting
- puppet_modules/finder.rb: Add docu for functions
- puppet_modules/finder.rb: Spec: Why call it `get_module` and not just use an `attr_reader` called `puppet_module`?
- puppet_modules/finder.rb: supported_os_list: could use `flat_map`:
```rb
        metadata['operatingsystem_support'].flat_map do |item|
          item[:operatingsystemrelease].map do |release|
            {:operatingssystem => item[:operatingsystem], :operatingsystemrelease => release}
          end
        end
```
- puppet_modules/spec_runner.rb: Remove empty line 4
- puppet_modules/spec_runner.rb: summary: Remove empty first line
- puppet_modules/spec_runner.rb: summary: Use https://github.com/hpoydar/chronic_duration ?
- puppet_modules/spec_runner.rb: ExampleResult: I found it a bit irritating that `stdout` is a parsed JSON hash. How about parsing the plain stdout string in the constructor of the ExampleResult?
- puppet_modules/spec_runner.rb: run_in_box: Let's use komenda! We can also use it in `VagrantBox::execute_local`. I will add EventEmitter…

**Comment by ppp0** [comment]
dobrze rabota! good robot!

**Comment by tomaszdurka** [comment]
@njam @ppp0 please review

**Comment by tomaszdurka** [comment]
Btw I've used `colorize` gem to make it look a bit more shiny (separate specs more clearly), but it doesn't look good on CI.

Should I drop it? :(((

**Comment by njam** [comment]
- Let's drop colors! :'(
- lib/vagrant.rb: Can now output just `result.output`, instead of separate stderr and stdout
- finder.rb: puppet_modules: Add newline before method
- spec_runner.rb: run_spec_in_box: Pass command as array to Komenda (`['bundle', 'exec', 'rspec']`), to avoid having to escape arguments
- spec_runner.rb: run_spec_in_box: We don't want to diplay STDOUT of the spec?

Rest looks good

**Comment by tomaszdurka** [comment]
> spec_runner.rb: run_spec_in_box: We don't want to diplay STDOUT of the spec?

Well this is due to using json format. Only output now is json result of the rspec. We don't want to show that. All other data is send to stderr (introduced here tomaszdurka@ca533ff).

Rest adjusted.

**Comment by njam** [comment]
lgtm!

Revert the change in mod/ssl/spec.rb and merge?

**Comment by tomaszdurka** [comment]
Btw I can still see some output malformation. Puppet produces colorized content too.

What about adding colors back and adding this for `build-ci` output?
http://unix.stackexchange.com/questions/4527/program-that-passes-stdin-to-stdout-with-color-codes-stripped
Anyway if yes it's low-priority and should be done in other, future pull-request.

**Comment by njam** [comment]
or the other way around?
https://github.com/dblock/jenkins-ansicolor-plugin

Let's leave the color, I will look into it?

**Comment by tomaszdurka** [comment]
So shall I revert https://github.com/tomaszdurka/puppet-packages/commit/5d2ed7df5eb6dbedca6361d7bb0e4092fd182da1?

**Comment by njam** [comment]
yes, let's keep color

**Comment by njam** [comment]
retest this please

**Comment by ppp0** [comment]
:rainbow: color !

**Comment by njam** [comment]
@tomaszdurka good to merge?

**Pull request merged**
