### PR TITLE
Use deb for ffmpeg (instead of building)

### PR DESCRIPTION
**Pull request by ppp0**
Depends on https://github.com/cargomedia/debian-packages/pull/82
Depends on https://github.com/cargomedia/debian-packages/pull/89

### CODE REVIEW

**Comment by ppp0** [comment]
waiting for  cargomedia/debian-packages#89

**Comment by ppp0** [comment]
please retest this

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
@ppp0 can you look into this? Will speed up builds.

**Comment by ppp0** [comment]
@njam said in https://github.com/cargomedia/puppet-packages/issues/1208#issue-140633036

> When migrating please delete the old binaries (`/usr/local/bin/ff*`?).

**Comment by ppp0** [comment]
retest this please (cache on ci manually purged)

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
:cry: bug https://github.com/cargomedia/puppet-packages/issues/1188 hitting me (us?) again

**Comment by njam** [comment]
Should be easy to fix, probably a one liner using `reject`? ;)

**Comment by ppp0** [comment]
waiting for #1188 to be able to run CI

**Comment by njam** [comment]
can you get this ready? compiling takes ages… :|

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
@njam last review?

**Comment by njam** [comment]
- deb_multimedia: init is still there
- Can we remove yasm?

**Comment by ppp0** [comment]
* ooops :)
* checked debian-packages puppet, too (used for provisioning VM) - can be removed

@njam should be fine, now

**Comment by njam** [comment]
lgtm!

Please remember to clean up production servers once released (let's do it tomorrow!)

**Comment by ppp0** [comment]
redeployed on janus2 and janus4

**Pull request merged**
