### PR TITLE
Upgrade jenkins to v2.x

### PR DESCRIPTION
**Pull request by njam**
Unattended upgrade failed

### CODE REVIEW

**Comment by njam** [comment]
@ppp0 please review

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
Looks like jenkin's plugin server is a bit overloaded.

retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
lgtm

**Comment by njam** [comment]
Specs failing because jenkins servers are having problems.
Will merge this, once puppet-cargomedia change is ready.

**Pull request merged**
