### PR TITLE
Change download url for flexjson.jar, because sourceforge is down

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab please review

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by NicolasSchmutz** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by NicolasSchmutz** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by NicolasSchmutz** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
self merging, fixing the build..

**Pull request merged**
