### PR TITLE
Add janus_cluster module

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
lgtm

**Comment by ppp0** [comment]
lgtm (Debian 8)

**Comment by tomaszdurka** [comment]
- Add monit entry

**Comment by ppp0** [comment]
oh, true :)

And a logrotator?
```
 logrotate::entry { $module_name:
    path    => $log_file,
    require => File[$log_file],
  }
```

**Comment by ppp0** [comment]
monit entry is provided by the `daemon` class!

**Comment by tomaszdurka** [comment]
There is no log yet.

**Pull request merged**
