### PR TITLE
Make puppet $vardir world readable

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look; this is the easiest working way!

**Comment by njam** [comment]
Add an assertion to the agent spec, with a note that we want `/var/lib/puppet/state` to be world-readable?

**Comment by njam** [comment]
Owner should be puppet

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
