### PR TITLE
Jessie: downgrade imagemagick to 8:6.8.9.9-5+deb8u2

### PR DESCRIPTION
**Pull request by kris-lab**
Addressing https://github.com/cargomedia/sk/issues/3831

```
# cat /etc/apt/preferences.d/imagemagick 
Package: imagemagick-common
Pin: version 8:6.8.9.9-5+deb8u2
Pin-Priority: 1001

Package: libmagickcore-6.q16-2
Pin: version 8:6.8.9.9-5+deb8u2
Pin-Priority: 1001

Package: libmagickwand-6.q16-2
Pin: version 8:6.8.9.9-5+deb8u2
Pin-Priority: 1001
```

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam wdyt in general? I cannot integrate `apt-::preference` into `php:: extension::imagick` because of dependencies cycle!

**Comment by njam** [comment]
I think this should not go to the "apt" module - it just *uses* it, but is not part of it.

Inside `php5::extension::imagick` would be the best I think. What's the cycle? `apt`? Probably `apt::preference` should not require `apt` (the only resource it declares - file - already has correct ordering to `Exec['apt_update']`).

**Comment by kris-lab** [comment]
I have found `apt::preference::<package>` similar to `apt::source::<repo>`. Anyway the problem is like follows
```
(Exec[/usr/lib/php5/extensions] => Class[Php5] => Class[Php5::Extension::Imagick] => Apt::Preference[imagemagick-common] => File[/etc/apt/preferences.d/imagemagick-common.pref] => Exec[apt_update] => Package[php5-common] => Class[Php5])
```
... due to `Class[Php5]` which doesn't make too much sense!

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
Failing specs resolved at https://github.com/cargomedia/bipbip/pull/162

**Comment by kris-lab** [comment]
retest this please

**Comment by ppp0** [comment]
lvgtm!

**Pull request merged**
