### PR TITLE
Implement foreman-systemd helper cli

### PR DESCRIPTION
**Pull request by tomaszdurka**
Current help output:
```
root@debian-8-amd64-plain:~# foreman-systemd
Missing <command> param

Usage:
  foreman-systemd install [-u <user>] [-f <formation>] [-l <location>] [-w <wanted-by>] <app-name> <root-dir>
  foreman-systemd start <app-name>
  foreman-systemd stop <app-name>
  foreman-systemd reload [-u <user>] [-f <formation>] [-l <location>] [-w <wanted-by>] <app-name> <root-dir>
```

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Did some manual testing

```shell
root@debian-8-amd64-plain:/etc/systemd/system# mkdir -p /tmp/app
root@debian-8-amd64-plain:/etc/systemd/system# echo "foo: bash -c \"while true; do echo 123; sleep; done\"" > /tmp/app/Procfile 
root@debian-8-amd64-plain:/etc/systemd/system# foreman-systemd install -u root -f all=1 -l /etc/systemd/system -w cm-applications.target sk /tmp/app
[foreman export] writing: app-sk-foo@.service
[foreman export] creating: app-sk-foo.target.wants
[foreman export] symlinking: app-sk-foo.target.wants/app-sk-foo@5000.service -> ../app-sk-foo@.service
[foreman export] writing: app-sk-foo.target
[foreman export] writing: app-sk.target
root@debian-8-amd64-plain:/etc/systemd/system# ls -al 
total 76
-rw-r--r--  1 root root  303 Sep 13 13:16 app-sk-foo@.service
-rw-r--r--  1 root root   28 Sep 13 13:16 app-sk-foo.target
drwxr-xr-x  2 root root 4096 Sep 13 13:16 app-sk-foo.target.wants
root@debian-8-amd64-plain:/etc/systemd/system# ls -al cm-applications.target.d/
total 12
drwxr-xr-x  2 root root 4096 Sep 13 13:16 .
drwxr-xr-x 15 root root 4096 Sep 13 13:16 ..
-rw-r--r--  1 root root   27 Sep 13 13:16 wants-app-sk.target.conf
root@debian-8-amd64-plain:/etc/systemd/system# cat cm-applications.target.d/*
[Unit]
Wants=app-sk.target
root@debian-8-amd64-plain:/etc/systemd/system# systemctl start app-sk.target
root@debian-8-amd64-plain:/etc/systemd/system# systemctl list-dependencies app-sk.target
app-sk.target
● └─app-sk-foo.target
●   └─app-sk-foo@5000.service
root@debian-8-amd64-plain:/etc/systemd/system# systemctl list-dependencies cm-applications.target
cm-applications.target
● └─app-sk.target
●   └─app-sk-foo.target
●     └─app-sk-foo@5000.service
```

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by tomaszdurka** [comment]
Failing test passed - merging.

**Pull request merged**
