### PR TITLE
Introduce OS filter for running specs

### PR DESCRIPTION
**Pull request by tomaszdurka**
@njam fyi

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka ready?

**Comment by tomaszdurka** [comment]
Yes,

**Comment by tomaszdurka** [comment]
usage:
```
bundle exec rake spec os_filter='Ubuntu-1504, Debian-7'
```

@njam wdyt? 
Please review.

**Comment by njam** [comment]
lgtm

@ppp0 wanna double check?

**Comment by ppp0** [comment]
* may be use `os` instead of `os_filter` ? (less to type)
* I took liberty to edit the README file here (and the mentioned install script)
@tomaszdurka please double-check and change either code or readme? (Depending on your choice `os`, `os_filter`)

otherwise lgtm!

**Comment by tomaszdurka** [comment]
What's the status of this one?

**Comment by njam** [comment]
There are a few different things mixed together in this PR. Also seems the naming of the parameter is not consistent?
@tomaszdurka , @ppp0 who will finish this up?

**Comment by tomaszdurka** [comment]
Paired with @njam

**Pull request merged**
