### PR TITLE
Verify if "sysctl::entry" is applied initially, after change and on reboot

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam @ppp0 I have added new spec and some refactoring, but I cannot reproduce the problem we experience on production. Entries have been always properly applied. wdyt?

**Comment by kris-lab** [comment]
Sorry guys for confusing you. I have double checked and I can reproduce this problem. Missing `.conf` is the reason for not applying the config after reboot.

@njam @ppp0 please review

**Comment by njam** [comment]
👍 lgtm

**Comment by njam** [comment]
I think old files are still on production.
Maybe delete them everywhere to avoid confusion?

**Comment by kris-lab** [comment]
Will run to cleanup:
```
find /etc/sysctl.d/ -type f ! -name "*.*" -delete
```

**Comment by kris-lab** [comment]
Done!

**Pull request merged**
