### PR TITLE
Configure "start-stop-daemon" stop-schedule *without* signal 9

### PR DESCRIPTION
**Pull request by tomaszdurka**
To avoid zombies

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Waiting on tests.

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
- The goal would be to *not* use the `KILL` signal. So the pattern should be `TERM/20/TERM/20` and not `TERM/20/KILL/20`? See also https://github.com/cargomedia/foreman-debian/blob/master/templates/initd_script.erb#L39
- mongodb, pulsar-rest-api and puppetdb tests fail. Is it related?

**Comment by njam** [comment]
@tomaszdurka could you finish this up?

Also streamline `--oknodo`?

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
- socket_redis/templates/init.sh: Formatting

rest looks good

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by tomaszdurka** [comment]
retest this please

**Comment by njam** [comment]
@tomaszdurka build failed, can you check?

**Comment by tomaszdurka** [comment]
We are checking it.

**Comment by tomaszdurka** [comment]
Merging as build failing cause of #797

**Pull request merged**
