### PR TITLE
Janus/rtp: add "hostname" configuration - update config files

### PR DESCRIPTION
**Pull request by kris-lab**
https://github.com/cargomedia/janus-gateway-rtpbroadcast#configuration
```
[general]
; Hostname to use. Will be used in API responses.
; hostname = localhost
```

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam have a look please. I have updated list of config options + I have made `hostname` mandatory in role `standalone` as it must be passed down to the `rtp` plugin. wdyt?

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
@njam please have a look on 2 last commits., thx

**Comment by njam** [comment]
lgtm

**Pull request merged**
