### PR TITLE
Use fluentd json parser for cm-janus

### PR DESCRIPTION
**Pull request by njam**
For https://github.com/cargomedia/cm-janus/issues/213

https://github.com/tagomoris/fluent-plugin-parser

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka please review

@vogdb fyi

**Comment by vogdb** [comment]
I'm afraid that soon Tomasz will have an allergy on `please review`

**Comment by vogdb** [comment]
or at least a filter in mailbox :D

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by dlondero** [comment]
Retest this please

**Comment by njam** [comment]
@kris-lab @ppp0 could you review this?

Adding fluentd configuration for cm-janus.

**Comment by kris-lab** [comment]
looks good to me. btw: they really store position of last read in `pos_file`; interesting!

**Comment by njam** [comment]
Yes, I guess if fluentd restarts this way they know where to continue reading.

**Pull request merged**
