### PR TITLE
Return second since epoch for "apt_cache_age" if no update stamp present

### PR DESCRIPTION
**Pull request by njam**
@kris-lab please review

### CODE REVIEW

**Comment by njam** [comment]
At the moment the function will return `0` if no update has ever ran, which makes `apt::update` to not run if no update has ever ran.

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
code looks good to me

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
@kris-lab please review

**Pull request merged**
