### PR TITLE
Configure puppet-master / librarian-puppet to rsync by default

### PR DESCRIPTION
**Pull request by kris-lab**
part of https://github.com/cargomedia/puppet-cargomedia/issues/746

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam wdyt? maybe it should go to librarian module and be configured globally for root?

**Comment by kris-lab** [comment]
retest this please

**Comment by njam** [comment]
- Shouldn't this go to `puppet::master::puppetfile`?
- Spec: Check whether config is really set and applied with `librarian-puppet config KEY`?

**Comment by kris-lab** [comment]
@njam what bout introducing `librarian_puppet::config`? The code should be tuned and optimised but wdyt in general?

**Comment by njam** [comment]
lvgtm, I would:
- replace $environment with $user_home (because it's the only usage?)

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- Could we use `exec`'s `cwd` argument instead of `cd`'ing?
- specs fail

**Comment by kris-lab** [comment]
@njam please review; only puppetdb test fails!

**Comment by njam** [comment]
One more thing (sorry):
- puppet::master::puppetfile: I'm not sure about the `$librarian_config` param, it requires to know internals of the class (the `/etc/puppet` path). How about just hardcoding these settings in the class? I don't think any other settings make sense?

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- `librarian_puppet::config`'s title should be `rsync for /etc/puppet` to avoid conflicts?

Rest look sgood!

**Comment by kris-lab** [comment]
agree. @njam please re-review...

**Comment by njam** [comment]
Looks good!
Let's hope this helps!

**Pull request merged**
