### PR TITLE
Add browserify cli support

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
The spec is failing (wrong module name?)

Let's also add a spec to ensure the command line tool is available and working, like:
```
  describe command('autoprefixer --version') do
    its(:exit_status) { should eq 0 }
    its(:stdout) { should match 'autoprefixer' }
  end
```

**Comment by ppp0** [comment]
to me, it looks very good!

**Comment by njam** [comment]
I recommended not to test for a specific version because then we need to update the tests when we upgrade the version… :D
lgtm

**Comment by zazabe** [comment]
@ppp0 i don't have write access on this repo, could you merge this PR?

**Pull request merged**
