### PR TITLE
Define for composer create-project

### PR DESCRIPTION
**Pull request by tomaszdurka**
Something like
```pp
composer::project { $repository:
  ensure => present,
  source => 'cargomedia/s3export_backup'
  target => $path,
  dev    => true,
}
```

would come in handy!

---

Should also update to certain version via `git`. See `class satis`:
```pp
  exec {'install satis':
    command => 'composer --no-interaction create-project composer/satis --stability=dev --keep-vcs /var/lib/satis/satis',
    creates => '/var/lib/satis/satis',
    path => ['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin'],
    user => 'satis',
    environment => ['HOME=/var/lib/satis'],
  }
  ->

  exec {'upgrade satis':
    command => "git fetch && git checkout ${version} && composer --no-interaction --no-dev install",
    cwd => '/var/lib/satis/satis',
    unless => "test $(git rev-parse HEAD) = ${version}",
    path => ['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin'],
    user => 'satis',
    environment => ['HOME=/var/lib/satis'],
  }
```

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 I know we did that almost yesterday - but I took liberty to push it. Please review :panda_face:

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
LvGTM

**Comment by njam** [comment]
Can we use it for satis as well?

**Comment by tomaszdurka** [comment]
Yes, done in https://github.com/cargomedia/puppet-packages/pull/821.

**Pull request merged**
