### PR TITLE
Updated janus/plugin configs

### PR DESCRIPTION
**Pull request by kris-lab**
- https://github.com/cargomedia/janus-gateway-audioroom/blob/master/conf/janus.plugin.cm.audioroom.cfg.sample#L15
- https://github.com/cargomedia/janus-gateway-rtpbroadcast/blob/master/conf/janus.plugin.cm.rtpbroadcast.cfg.sample#L32

### CODE REVIEW

**Comment by kris-lab** [comment]
@ppp0 please review

**Comment by njam** [comment]
Hm, how did it even work with `bind_address       => '127.0.0.1',`?

Shouldn't this recording be boolean in puppet?

**Comment by kris-lab** [comment]
> Shouldn't this recording be boolean in puppet?
Well so far we use it as `yes/no` with e.g. transport. I thought to keep it consistent?

> Hm, how did it even work with bind_address => '127.0.0.1',?

ok SHIT:) this is bug, thx

**Comment by kris-lab** [comment]
> Shouldn't this recording be boolean in puppet?

hmm no idea how it works. It is like that in the production...

**Comment by njam** [comment]
ok, lgtm

**Pull request merged**
