### PR TITLE
Add HSTS to cm::vhost

### PR DESCRIPTION
**Pull request by kris-lab**
Some notes:
- https://coderrr.wordpress.com/2010/12/27/canonical-redirect-pitfalls-with-http-strict-transport-security-and-some-solutions/
- http://linux-audit.com/configure-hsts-http-strict-transport-security-apache-nginx/

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam have a look;

tested on staging; seems to be working good!

**Comment by njam** [comment]
Should this only be enabled when using SSL?
What effect does the "max-age" have?

**Comment by kris-lab** [comment]
- agree
- "Max-age limits should be carefully considered as infrequent visitors may find your site inaccessible if you relax your policy." so in my understanding if we change back to use HTTP then browser could cache it and make inaccessible? ([see](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security))

@njam please re-review; (wdyt about passing empty string if ssl not enabled?)

**Comment by njam** [comment]
- So maybe reduce "max-age" a bit? 10 days?
- What about `includeSubdomains`? Since we're setting this for `example.com` this will also affect other sub domains that we possibly *don't* manage with this vhost (e.g. `ads.example.com` etc)
- I can see that our AWS CloudFront CDN is pulling over `http://` from the "cdn_origin_vhost".

Overall I now too have the feeling this is a bit dangerous due to the above if we don't thoroughly test it. Should we skip it?

**Comment by kris-lab** [comment]
Agree. Let's skip for now. 

closing.

**Pull request closed without merging**
