### PR TITLE
Migrate gearman service to daemon

### PR DESCRIPTION
**Pull request by ppp0**
needed by #1150

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- Delete monit and default template
- Why change `bind_ip`? This will probably affect our production as we don't define it (then it's all IPs?). I would suggest to keep default undefined?
- Now the package requires the daemon, shouldn't it be the other way around?
- Daemon should require package and log file

**Comment by ppp0** [comment]
* ok
* the listen-address was defined in `/etc/default` which is not anymore and it defaulted to `localhost`
* because package install starts the daemon and later we tweak the init files. Like this this won't happen
* see above, log file ok

**Comment by ppp0** [comment]
@njam please re-check

**Comment by njam** [comment]
- Ah, the log file wasn't managed. We can also leave it un-managed (let the DEB manage it)!

When I apply the module twice, on the second run I get:
```
Notice: /Stage[main]/Postfix/File[/etc/aliases]/content: content changed '{md5}2df59828c67bf5d820035fb6040abaa4' to '{md5}ceedf226bdeb70b3df7e013eddb2483d'
Notice: /Stage[main]/Postfix/Exec[newaliases]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Postfix::Service/Service[postfix]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Gearman::Server/File[/etc/default/gearman-job-server]/ensure: removed
Notice: /Stage[main]/Gearman::Server/File[/var/log/gearman-job-server]/owner: owner changed 'gearman' to 'root'
Notice: /Stage[main]/Gearman::Server/File[/var/log/gearman-job-server]/group: group changed 'gearman' to 'root'
```

Can you look into those? (preferably everything should be in the desired state on the first run)

**Comment by ppp0** [comment]
>When I apply the module twice, on the second run I get:

Which spec test is it happening on? I can't reproduce this. I believe it had to do with the log file which is not anymore?

@njam please review

**Comment by njam** [comment]
Still happening:
```
$ bundle exec rake spec:gearman:server keep_box=true
Running gearman:server for Debian-7
vagrant ssh-config Debian-7 > /var/folders/_8/70bmqjtd7h3cm6wzlm_bbchh0000gn/T/20160217-41760-rk17pi
Puppet applying: `/vagrant/modules/gearman/spec/server/manifest.pp`
Notice: Compiled catalog for debian-7-amd64-default.vagrantup.com in environment production in 1.17 seconds
Notice: /Stage[main]/Postfix/File[/etc/aliases]/content: content changed '{md5}2df59828c67bf5d820035fb6040abaa4' to '{md5}ceedf226bdeb70b3df7e013eddb2483d'
Notice: /Stage[main]/Postfix/Exec[newaliases]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Postfix::Service/Service[postfix]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Gearman::Server/File[/etc/default/gearman-job-server]/ensure: removed
Notice: Finished catalog run in 0.48 seconds
vagrant ssh-config Debian-7 > /var/folders/_8/70bmqjtd7h3cm6wzlm_bbchh0000gn/T/20160217-41760-1t86498
Success! 7 examples, 0 failures

Running gearman:server for Debian-8
vagrant ssh-config Debian-8 > /var/folders/_8/70bmqjtd7h3cm6wzlm_bbchh0000gn/T/20160217-41792-vkht69
Puppet applying: `/vagrant/modules/gearman/spec/server/manifest.pp`
Notice: Compiled catalog for debian-8-amd64-default.vagrantup.com in environment production in 1.13 seconds
Notice: /Stage[main]/Postfix/File[/etc/aliases]/content: content changed '{md5}2df59828c67bf5d820035fb6040abaa4' to '{md5}ceedf226bdeb70b3df7e013eddb2483d'
Notice: /Stage[main]/Postfix/Exec[newaliases]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Postfix::Service/Service[postfix]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Gearman::Server/File[/etc/default/gearman-job-server]/ensure: removed
Notice: Finished catalog run in 0.64 seconds
vagrant ssh-config Debian-8 > /var/folders/_8/70bmqjtd7h3cm6wzlm_bbchh0000gn/T/20160217-41792-qqkrkz
Success! 7 examples, 0 failures
```

**Comment by ppp0** [comment]
Alright, I removed deletion of the now obsoleted `/etc/default/gearman-job-server` which is not referenced anymore. There still is the postfix alias file which gets touched somewhere and will be restored at a second run. I believe this must have to do with monit somehow

first run:
```
Notice: /Stage[main]/Postfix/File[/etc/aliases]/content: content changed '{md5}745361bb155f3598dd29c6c0c59128d5' to '{md5}ceedf226bdeb70b3df7e013eddb2483d'
```

2nd run:
```
Notice: /Stage[main]/Postfix/File[/etc/aliases]/content: content changed '{md5}2df59828c67bf5d820035fb6040abaa4' to '{md5}ceedf226bdeb70b3df7e013eddb2483d'
````

I'd say this is not directly related to gearman, though.

@njam agree?

**Comment by njam** [comment]
Agree! Opened a separate ticket - can you look into it? https://github.com/cargomedia/puppet-packages/issues/1169

This one lgtm

**Pull request merged**
