### PR TITLE
Add bipbip entry for socket-redis

### PR DESCRIPTION
**Pull request by kris-lab**
Depends on https://github.com/cargomedia/bipbip/pull/100

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- Dash is not allowed in resource name?
- Use host+port config and pass it on to bipbip

**Comment by kris-lab** [comment]
* ok
* ok: socket-redis host is not a class arguments so will use localhost (only redis host is known)

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- Now you can drop the `plugin` key
- url key should be prefixed with `http://`?

**Comment by kris-lab** [comment]
* we use `plugin` key everywhere!?
* `http://` is not needed imo; it uses http transportation by default

**Comment by kris-lab** [comment]
@njam please review?

**Comment by njam** [comment]
lgtm!

**Pull request merged**
