### PR TITLE
SYS-184 Introduce fluentd logfile source

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
FYI, multiline support is useful for mysql slow query log for example

**Comment by ppp0** [comment]
Build fails on lint with "modules/fluentd/spec/source_logfile/1-manifest.pp - WARNING: double quoted string containing no variables on line 29"

**Comment by ppp0** [comment]
Add realization to init.pp as in https://github.com/cargomedia/puppet-packages/blob/master/modules/fluentd/manifests/init.pp#L59
` Fluentd::Config::Source_logfile <||> `

**Comment by ppp0** [comment]
@{f4355e77-07da-4ca6-b033-d106f96ec3bb,Michel Meyer} can you have a final look please?

**Pull request merged**
