### PR TITLE
Add jenkins slave module

### PR DESCRIPTION
**Pull request by njam**
Summary:
- Refactor jenkins config manifests
- Change all parameters to lowercase (according to puppet language specification). Not doing so will result in errors when using exported resources! :warning: 
- Introduce `jenkins::slave` module to install a slave for a jenkins cluster
- Introduce `jenkins::config::slave` which is the configuration of such a slave on the master (exported resource from `jenkins::slave` which will be collected in `jenkins`).

screen shot 2015-01-11 at 16 52 39

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab @ppp0 @tomaszdurka please review

I'm planning to add slave nodes for jenkins.
There's some docu on basic usage [in the module directory](https://github.com/njam/puppet-packages/blob/jenkins-distributed/modules/jenkins/README.md).

All jenkins specs succeed.

**Comment by njam** [comment]
...lmk if I should guide you through the code!

**Comment by kris-lab** [comment]
I am not very much into jenkins topics; if you have a time I would be happy to get some guide!

**Comment by njam** [comment]
@kris-lab will review

**Comment by kris-lab** [comment]
afaics and test it looks good to me.

**Pull request merged**
