### PR TITLE
Add phantomjs to cm in dev

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@ppp0 please review

I tried to test it with `bundle exec rake spec:cm debug=true`, but it seems there's no specs to test this module in dev (I can't see the step when `phantomjs` is installed), did I miss something?

**Comment by njam** [comment]
I think there is no spec where we pass `$development => true` to `cm::application`.

**Comment by zazabe** [comment]
@ppp0 could you merge it also if it's okay (I don't have write access to this repo)?

**Comment by ppp0** [comment]
So you don't want to write a spec? 😄

**Pull request merged**
