### PR TITLE
Debian-8: multiple packages upgrade - part 1

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1363

### CODE REVIEW

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
@njam @ppp0 please review

**Comment by ppp0** [comment]
lgtm!

**Comment by njam** [comment]
lgtm

**Pull request merged**
