### PR TITLE
Fix puppet-db specs

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by njam** [comment]
Are you sure `apt-get install` is considering this variable?
For `apt-get update` we set this special option in `hiera.json`:
```
  "apt::update::options": [
    "Acquire::http::proxy=false"
  ],
```

**Comment by ppp0** [comment]
We tried and disabled the setting in `/etc/apt/apt.conf.d/01proxy` but did not see any change in behaviour.. tbh I can't recall if it was on `update` or `install` (does it make a difference?)

**Comment by ppp0** [comment]
What we can say is that without proxy it works. Not clear if polipo or apt-get is to blame, though

**Comment by tomaszdurka** [comment]
Depends on #871

**Comment by ppp0** [comment]
Aha? Build succeeds

**Comment by tomaszdurka** [comment]
It works with retries as you see. But actually I've seen it failing locally with retries too (20 times could not get resource).

I would actially disable proxy instead.

**Comment by tomaszdurka** [comment]
As seen in newest build:
```
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
Err http://apt.puppetlabs.com/ wheezy/main puppetdb all 2.2.2-1puppetlabs1
  Connection failed [IP: 127.0.0.1 8123]
```

Let's disable proxy.

**Comment by tomaszdurka** [comment]
Merging @ppp0 changes.

**Comment by njam** [comment]
fingers crossed

**Pull request merged**
