### PR TITLE
Update MMS agents (backup, monitoring)

### PR DESCRIPTION
**Pull request by ppp0**
Upgrade to
Monitoring current: 3.7.0.212
Backup current: 3.7.0.304

### CODE REVIEW

**Comment by ppp0** [comment]
@tomaszdurka please review
or @njam ?

**Comment by njam** [comment]
Install scripts fail in build!

**Comment by tomaszdurka** [comment]
Aye http://ci.cargomedia.ch:8080/job/cargomedia-puppet-packages-pr/279/console

**Comment by ppp0** [comment]
This is weird.. I checked the url - looks good. I suspect it's because of the `curl` failing? Will check later

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
lgtm

**Pull request merged**
