### PR TITLE
Experiments: added opencv and cuda modules skeleton

### PR DESCRIPTION
**Pull request by kris-lab**
(notes)
Currently, this is for documentation purpose only... If really needed we can add custom DEB for OpenCV with GPU acceleration.

How to revert changes on bulldogs:
```
SOME NVIDIA DERIVERS HAS BEEN REMOVED FROM BULLDOG - TRANSITION TO CUDA

----------------------------------------------------------------------

The following extra packages will be installed:
  cuda-7-5 cuda-command-line-tools-7-5 cuda-core-7-5 cuda-cublas-7-5 cuda-cublas-dev-7-5 cuda-cudart-7-5 cuda-cudart-dev-7-5 cuda-cufft-7-5
  cuda-cufft-dev-7-5 cuda-curand-7-5 cuda-curand-dev-7-5 cuda-cusolver-7-5 cuda-cusolver-dev-7-5 cuda-cusparse-7-5 cuda-cusparse-dev-7-5
  cuda-documentation-7-5 cuda-driver-dev-7-5 cuda-drivers cuda-license-7-5 cuda-misc-headers-7-5 cuda-npp-7-5 cuda-npp-dev-7-5
  cuda-nvrtc-7-5 cuda-nvrtc-dev-7-5 cuda-runtime-7-5 cuda-samples-7-5 cuda-toolkit-7-5 cuda-visual-tools-7-5 freeglut3 freeglut3-dev
  libcuda1-352 libxmu-dev libxmu-headers libxt-dev nvidia-352 nvidia-352-dev nvidia-352-uvm nvidia-modprobe nvidia-opencl-icd-352
  nvidia-settings
Suggested packages:
  libxt-doc
The following packages will be REMOVED:
  libcuda1-346 nvidia-346 nvidia-opencl-icd-346
The following NEW packages will be installed:
  cuda cuda-7-5 cuda-command-line-tools-7-5 cuda-core-7-5 cuda-cublas-7-5 cuda-cublas-dev-7-5 cuda-cudart-7-5 cuda-cudart-dev-7-5
  cuda-cufft-7-5 cuda-cufft-dev-7-5 cuda-curand-7-5 cuda-curand-dev-7-5 cuda-cusolver-7-5 cuda-cusolver-dev-7-5 cuda-cusparse-7-5
  cuda-cusparse-dev-7-5 cuda-documentation-7-5 cuda-driver-dev-7-5 cuda-drivers cuda-license-7-5 cuda-misc-headers-7-5 cuda-npp-7-5
  cuda-npp-dev-7-5 cuda-nvrtc-7-5 cuda-nvrtc-dev-7-5 cuda-runtime-7-5 cuda-samples-7-5 cuda-toolkit-7-5 cuda-visual-tools-7-5 freeglut3
  freeglut3-dev libcuda1-352 libxmu-dev libxmu-headers libxt-dev nvidia-352 nvidia-352-dev nvidia-352-uvm nvidia-modprobe
  nvidia-opencl-icd-352
The following packages will be upgraded:
  nvidia-settings
1 upgraded, 40 newly installed, 3 to remove and 5 not upgraded.

----------------------------------------------------------------------

DKMS: install completed.
Setting up nvidia-352-uvm (352.39-0ubuntu1) ...
Setting up nvidia-352-dev (352.39-0ubuntu1) ...
Setting up nvidia-modprobe (352.39-0ubuntu1) ...
Setting up nvidia-settings (352.39-0ubuntu1) ...
Setting up libcuda1-352 (352.39-0ubuntu1) ...
Setting up nvidia-opencl-icd-352 (352.39-0ubuntu1) ...
Setting up cuda-drivers (352.39-1) ...
Setting up cuda-runtime-7-5 (7.5-18) ...
Setting up cuda-7-5 (7.5-18) ...
```

### CODE REVIEW

**Comment by kris-lab** [comment]
#### EXPERIMENT PLAN:

- INSTALL CUDA
 - source: https://developer.nvidia.com/cuda-downloads
 - manual: https://github.com/facebook/fbcunn/blob/master/INSTALL.md

- INSTALL OpenCV with GPU+CUDA...
 - http://blog.aicry.com/ubuntu-14-04-install-opencv-with-cuda/

- VERIFY
 - https://help.ubuntu.com/community/OpenCV
 - https://github.com/opencv/opencv/tree/master/samples/gpu/
 - http://docs.opencv.org/2.4/doc/tutorials/gpu/gpu-basics-similarity/gpu-basics-similarity.html#gpubasicssimilarity

**Comment by kris-lab** [comment]
Results:
- Ubuntu 15.04 with CUDA 7.5 and Nvidia driver 352 is compilable
- OpenCV 3.0.0 is compilable (took more than 1h)
- OpenCV GPU sample are working properly - some "stereo matching" example - **very high frame rate (depends on disparity level)** , quality of provided images is pretty bad, but it still works...

```bash
DISPLAY=:0 XAUTHORITY=/home/admin/.Xauthority \
  ./bin/gpu-example-stereo_match \
  --left ../samples/data/right.jpg \
  --right ../samples/data/left.jpg \
  --method BM \
  --ndisp 256
```

I have provided left and right image:
right

Results of 3D depth:
screen shot 2016-08-10 at 14 27 21

- it would work much better with higher resolution
- it would work much better without green background

**Comment by kris-lab** [comment]
Reinstalling all with `OpenCV@2.4.9.1` because of Gstreamer limitation `opencv >= 2.3.0 opencv < 2.5.0`

The flag `-D CUDA_GENERATION=Kepler` needs to be additionally added to make opencv compilable. It was not needed with `OpenCV@3.0`.

```
# download OpenCV source code ./opencv
cd opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=1 -D CUDA_GENERATION=Kepler .. 
make
make install
```

**Comment by kris-lab** [comment]
Making compilation `OpenCV@2.4.9.1` compatible with `gst-plugins-bad@1.8.0`:
```bash
# some reason Gstreamer used package config from version installed by apt-get opencv@2.4.9
# it makes confusion with paths. Opencv libs installed manually goes to /usr/lib/x86_64-linux-gnu/
ln -s  /usr/lib/x86_64-linux-gnu/pkgconfig/opencv.pc  /usr/local/lib/pkgconfig/opencv.pc

# Linked missing CUDA libs in Gstreamer/OpenCV plugin
# CUDA must be installed separately
ln -s /usr/local/cuda-7.5/targets/x86_64-linux/lib/libcufft.so /usr/local/lib/
ln -s /usr/local/cuda-7.5/targets/x86_64-linux/lib/libnpps.so /usr/local/lib/
ln -s /usr/local/cuda-7.5/targets/x86_64-linux/lib/libcublas.so /usr/local/lib/
ln -s /usr/local/cuda-7.5/targets/x86_64-linux/lib/libnppi.so /usr/local/lib/
ln -s /usr/local/cuda-7.5/targets/x86_64-linux/lib/libnppc.so /usr/local/lib/
ln -s /usr/local/cuda-7.5/targets/x86_64-linux/lib/libcudart.so /usr/local/lib/
```

**Comment by kris-lab** [comment]
I couldn't confirm that Gstreamer with OpenCV plugins run on the GPU with pipeline like follows:
````
DISPLAY=:0 XAUTHORITY=/home/performer/.Xauthority GST_GL_API=opengl \
  gst-launch-1.0 videotestsrc \
    ! video/x-raw,width=1920,height=1080,framerate=25000/1001 \
    ! facedetect 
    ! videoconvert 
    ! grabcut test-mode=true 
    ! progressreport 
    ! fakesink
```
where `facedetect` and `grabcut` are OpenCV plugins.

Checking of GPU ussage has been done with `nvidia-smi` - there was no `gst-launch` process which would confirm usage of GPU by pipeline (it happens if we use openGL plugins):
```
+------------------------------------------------------+                       
| NVIDIA-SMI 346.59     Driver Version: 346.59         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:0A:00.0     N/A |                  N/A |
|  0%   36C    P8    N/A /  N/A |     83MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0            C+G   Not Supported                                         |
+-----------------------------------------------------------------------------+
```


Possible errors:
- gstreamer doesn't load proper OpenCV libs?
- gstreamer is not compiled with proper OpenCV libs (very unlikely)
- OpenCV plugins are not using GPU accelerated features of OpenCV - not sure how it works internally, so it must be verified!

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
Closing as not needed at the moment

**Pull request closed without merging**
