### PR TITLE
Reduce janus log verbosity

### PR DESCRIPTION
**Pull request by kris-lab**
Currently the log is very verbose, which is not needed imo because we have most events already in cm-janus. 2 million events in the last 7 days.

@kris-lab Can we reduce the verbosity?

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review. I decided to not make it configurable. The verbosity level is downgraded to the WARN level.

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
Some specs are depending on level 4 output.
We either need to adjust those, or make it configurable?

**Comment by ppp0** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by kris-lab** [comment]
@njam please re-review

**Comment by njam** [comment]
I would call this "log_level", which is the common name for this.
Rest lgtm.

**Comment by kris-lab** [comment]
retest this please

**Pull request merged**
