### PR TITLE
Introduce systemd::critical_units package

### PR DESCRIPTION
**Pull request by tomaszdurka**
- Puppet class for a "critical" target in "systemd"
- Puppet "systemd::unit" should export a virtual resource, which will add a "Wants=" entry to the critical target

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
- systemd/manifests/critical_unit.pp: $serviceName: Isn't this rather a $unitName (it includes "service" in its name).
 - Same in systemd/manifests/unit.pp
- systemd/manifests/critical_units.pp: It it okay to purge the `.wants/` directory? How will pulsar register the application target?
- systemd/manifests/init.pp: Instead of `class{}` rather use `include` to avoid duplicate definitions if somebody would include the class in hiera?

**Comment by tomaszdurka** [comment]
> - systemd/manifests/critical_unit.pp: $serviceName: Isn't this rather a $unitName (it includes "service" in its name).
>  - Same in systemd/manifests/unit.pp

Sure!

> - systemd/manifests/critical_units.pp: It it okay to purge the `.wants/` directory? How will pulsar register the application target?
Valid point. I added it to actually remove those critical services we dropped. Any suggestions? Should we not purge? We could use `wants` option for that critical unit and let systemd create them? I think it would after reload.

> - systemd/manifests/init.pp: Instead of `class{}` rather use `include` to avoid duplicate definitions if somebody would include the class in hiera?

OK.

**Comment by njam** [comment]
> Should we not purge? We could use `wants` option for that critical unit and let systemd create them? I think it would after reload.

The plan is to use the `.wants/` directory for pulsar, right? Maybe test that before deciding here?
I don't think using the `Wants=` config file option will make a difference. It will be the same like not purging, right?

**Comment by tomaszdurka** [comment]
@njam please final check

**Comment by njam** [comment]
lgtm

**Pull request merged**
