### PR TITLE
Jenkins wants to run tests for deleted folders

### PR DESCRIPTION
**Pull request by ppp0**
To reproduce:

- remove a folder which had specs before
- PR

test run will fail (spec not found)

https://github.com/cargomedia/puppet-packages/blob/master/build-ci.sh#L18 should not run if there is a folder deletion

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
I would rather keep the raising behaviour of `puppet_module`, so that other usages fail early. Also I'm not sure if this even works, because `puppet_module` still returns a non-false value?

How about introducing `Finder#puppet_module?(name)` which return boolean, and then using it to filter the module list?
```ruby
module_list.select! { |module_name| finder.puppet_module?(module_name) }
```

**Comment by ppp0** [comment]
Ok then tomorrow

**Comment by ppp0** [comment]
Makes sense, @njam please review

**Comment by njam** [comment]
please adjust formatting in Rakefile

otherwise good to go

**Comment by njam** [comment]
lgtm

**Pull request merged**
