### PR TITLE
BO-83 Mysql systemd unit errors when starting

### PR DESCRIPTION
**Pull request by ppp0**
Starting the mysql unit:
```
systemctl start mysql.service
```

Results in strange errors in the systemd log:
```
Jan 24 09:49:00 www2 systemd[1]: Starting mysql...
Jan 24 09:49:00 www2 systemd[2085]: Failed at step RUNTIME_DIRECTORY spawning /usr/share/mysql/mysql-systemd-start: File exists
Jan 24 09:49:00 www2 systemd[1]: mysql.service: control process exited, code=exited status=233
Jan 24 09:49:00 www2 systemd[1]: Failed to start mysql.
Jan 24 09:49:00 www2 systemd[1]: Unit mysql.service entered failed state.
Jan 24 09:49:00 www2 systemd[1]: mysql.service holdoff time over, scheduling restart.
Jan 24 09:49:00 www2 systemd[1]: Stopping mysql...
Jan 24 09:49:00 www2 systemd[1]: Starting mysql...
Jan 24 09:49:02 www2 systemd[1]: Started mysql.
```

This leads to problems when upgrading the package - dpkg errors.

Unit:
```
# /etc/systemd/system/mysql.service
[Unit]
Description=mysql
After=network.target

[Service]
Type=simple
ExecStartPre=/usr/share/mysql/mysql-systemd-start pre
ExecStart=/usr/sbin/mysqld 
ExecStartPost=/usr/share/mysql/mysql-systemd-start post
User=mysql
PermissionsStartOnly=true
TimeoutStopSec=600
KillMode=mixed
Restart=always
LimitNOFILE=16384
RuntimeDirectory=mysqld
RuntimeDirectoryMode=0755
StandardOutput=null
StandardError=null

[Install]
WantedBy=multi-user.target
```

### CODE REVIEW

**Comment by ppp0** [comment]
[This feature / bugfix](https://github.com/systemd/systemd/commit/ce359e98f87c7fbe5aa1d275e43cf088ce46c2b0) would not hurt either (starting with v232)

**Comment by kris-lab** [comment]
> Rationale: mysql-5.7 is the first version that ships with a "native" systemd-based...

@ppp0 so what are recommended "steps list" for this change and transition + future apt upgrades?

**Comment by kris-lab** [comment]
As discussed, current changes don't solve the core problem, but it's good to sync the file with master.

It looks like RUNTIME_DIRECTORY is not released by `systemd` service tears down. As the result we run into time race condition.

**Comment by ppp0** [comment]
[notes to myself - to be investigated, looks interesting]
* https://dev.mysql.com/doc/refman/5.7/en/using-systemd.html#systemd-mysql-configuration
* https://dev.mysql.com/doc/refman/5.5/en/mysqld-safe.html#option_mysqld_safe_malloc-lib
* https://github.com/blog/1422-tcmalloc-and-mysql
* https://news.ycombinator.com/item?id=5260690

**Comment by ppp0** [comment]
interesting: if I remove the `runtime_directory` args, it works without problems (updates, restarts). I would suggest to remove it as it's unclear what its benefits are

@kris-lab please review

**Comment by kris-lab** [comment]
Agree on removing runtime directory. Official [docu](https://dev.mysql.com/doc/refman/5.7/en/using-systemd.html) says nothing about this + MariaDB says "remove all the RuntimeDirectory crap from systemd-units" -> https://lists.launchpad.net/maria-discuss/msg02959.html

**Comment by kris-lab** [comment]
The rest looks good. Please apply responsibly, it will restart services.

**Comment by ppp0** [comment]
Fully agree :) - I'd recommend the same procedure as for apt-upgrade, ie
* stop puppet on master/slaves
* app stop
* apply puppet on slaves
* apply puppet on master
* app start
* restore puppet daemon on all nodes

**Comment by ppp0** [comment]
lgtm

**Comment by kris-lab** [comment]
👍

**Pull request merged**
