### PR TITLE
Extend revealcloud copperegg-tags with server node specific tags (hiera)

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1622

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look

**Comment by kris-lab** [comment]
retest this please

**Comment by njam** [comment]
lgtm

Why did the build [get aborted](http://ci.cargomedia.ch:8080/job/cargomedia-puppet-packages-pr/517/console)?

**Comment by kris-lab** [comment]
Problems with VirtualBox. @ppp0 is working on this. 

I will re-test before merge.

**Comment by kris-lab** [comment]
retest this please

**Comment by ppp0** [comment]
@kris-lab cc - success!
screen shot 2016-11-21 at 13 28 32
screen shot 2016-11-21 at 13 28 14

**Pull request merged**
