### PR TITLE
Memcache for Jessie

### PR DESCRIPTION
**Pull request by kris-lab**
part of #1346

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
If we're not using *daemon* we will not have a monit entry. So on non-wheezy operating systems we will miss the monit entry now.
I think we could just include the monit entry always. Can we use `service memcached start` as a command in the monit entry that works on both sysvinit and systemd?

**Comment by kris-lab** [comment]
> Can we use service memcached start as a command in the monit entry that works on both sysvinit and systemd?

Not sure if I get it right... `service memcached start` works only with `systemd`, however `/etc/init.d/memcached  start` will work with both `systemd` and `sysvinit`. What is your question?

**Comment by njam** [comment]
As discussed we'll try using `daemon` to avoid having different monit entries for sysvinit/systemd.

**Comment by kris-lab** [comment]
@njam have a look please. Please note, I have removed `-d` option, which was breaking in `systemd` and doesn't have effect in `sysvinit`.

**Comment by njam** [comment]
What about `logfile /var/log/memcached.log`, I guess it's needed at least for wheezy?

**Comment by kris-lab** [comment]
Agree, this is bug. However it gets more complicated, because on `systemd` it works out of the box, but on `sysvinit` the have `cat /usr/share/memcached/scripts/start-memcached` wrapepr which creates `PIDFILE` and `LOGFILE`. If we wanna use custom script from `daemon`, we will have to re-use the `start-memcached` for wheezy. wdyt?

**Comment by njam** [comment]
I see!

How about we add a special case (`if`)  for wheezy, which would *not* use daemon, but the default package, and the monit entry? Then we can remove it once not needed anymore.

**Comment by kris-lab** [comment]
@njam have a look....

**Comment by njam** [comment]
lgtm

**Pull request merged**
