### PR TITLE
Add fluentd source for janus

### PR DESCRIPTION
**Pull request by njam**
See http://fluentular.herokuapp.com/parse?regexp=%28%5C%5B%28%3F%3Ctime%3E%5B%5E%5C%5D%5D%2B%29%5C%5D+%29%3F%28%3F%3Cmessage%3E.*%29&input=%5BFri+Apr++8+06%3A27%3A34+2016%5D+Creating+new+handle+in+session+246199357%3A+650711544%0D%0A&time_format=

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab please review

Timestamp is optional, see https://github.com/meetecho/janus-gateway/issues/498

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
