### PR TITLE
Run satis as a daemon/service instead of cron job

### PR DESCRIPTION
**Pull request by ppp0**
As discussed, we gain more control about handling error conditions if we run `satis` as a daemon
E.g. we can retry downloads a couple of times before throwing alerts

Continuation of #1312 #1327

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

The idea is to have a long-running daemon instead of a cron job which mails us in case of failures. Failures are, as we have seen, often due to github issues leading to network exceptions

**Comment by ppp0** [comment]
Sorry @kris-lab please consider only commit https://github.com/cargomedia/puppet-packages/pull/1328/commits/5db46c049aa9cd934df09af0f3dacea7cf6da429

**Comment by njam** [comment]
If upgrading the repo fails for a longer time, it interrupts developer workflows.
There fore I think we should retry a "couple of times", but then fail and inform a sysadmin.
Or maybe even detect some special errors (like github down) and ignore only those?

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
OK, so now the "daemon" is modify to ignore TransportException AND github.com - All others will result in a failure. A failure will dump the content of the error (temp) file to the journal and the "daemon" will be restarted by systemd as per our default (via `daemon` resource)

@kris-lab please review

**Comment by kris-lab** [comment]
Code looks good!

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
@ppp0  we get this error on build:
````
 Error: Command exceeded timeout
      Error: /Stage[main]/Satis/Composer::Project[composer/satis]/Exec[upgrade composer/satis]/returns: change from notrun to 0 failed: Command exceeded timeout
```
do you know why?

**Comment by ppp0** [comment]
I tried now several times both on my local VM and on ci5's (where the build failed) and is runs through... Really weird. Might be solved by https://github.com/cargomedia/puppet-packages/issues/885 ? I don't know. It looks like it's failing consistently on that `composer upgrade` step (as always, no comments about composer)

**Comment by ppp0** [comment]
Let's try with an updated satis version.. (see https://github.com/cargomedia/puppet-packages/pull/1328/commits/0749ac83047a45413de14a7e802865390c8085c6) - It helped on https://github.com/cargomedia/puppet-packages/issues/1005 and https://github.com/cargomedia/puppet-packages/pull/1023

**Comment by ppp0** [comment]
@kris-lab I can't believe it, but upgrading satis has helped. please review

**Comment by kris-lab** [comment]
ok! lgtm

**Pull request merged**
