### PR TITLE
Fix missing augeas double quotas

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam the problem is not in `puppet/ruby` which send proper values to the `augeas`. We have to set explicitly that we wanna have this quotas for non string values.

**Comment by njam** [comment]
Could we instead pass `value => '"true"'`?

**Comment by kris-lab** [comment]
@njam yes:) please re-review

**Comment by njam** [comment]
lgtm

**Pull request merged**
