### PR TITLE
Port janus and plugin modules to jessie

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by ppp0** [comment]
part of #1242

**Comment by njam** [comment]
Why change those specs? The old version covers more ground I think.
@kris-lab can you review this, as you're the original author?

**Comment by kris-lab** [comment]
@ppp I guess the only change is that you check all ports together for listening (not per janus process)?

**Comment by ppp0** [comment]
I did not change the specs just for fun. Under `systemd` - with our `daemon`-generated service description files - there is no such thing as a `PID` file, so the spec would break. `netstat` on the contrary, knows which port is listening and what process is bound to it. I cheerfully welcome better solutions

**Comment by ppp0** [comment]
spec fails because of https://github.com/cargomedia/puppet-packages/pull/1249 which is way more important than this PR here - @kris-lab please review

**Comment by kris-lab** [comment]
retest this please

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
lgtm

**Comment by njam** [comment]
Thanks for the explanation. A short note either as a comment or a commit message would be helpful, so the reviewer knows the reasoning if it's not obvious from the code.

Now we could probably also just use [serverspec's matcher](http://serverspec.org/resource_types.html#port):
```ruby
describe port(80) do
  it { should be_listening.with('tcp') }
end
```

**Comment by ppp0** [comment]
I thought about the matcher port(N) but since you can't give it a list of ports to check it would be too verbose for my taste

**Pull request merged**
