### PR TITLE
Move monit entry for daemon into sysvinit version only

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 pleae review

**Comment by ppp0** [comment]
makes sense, lgtm

**Comment by kris-lab** [comment]
@tomaszdurka what is the status here?

**Comment by tomaszdurka** [comment]
Oh, mergable - except build failed.
Will adjust and ask for review/

**Comment by tomaszdurka** [comment]
Checking status.

**Comment by tomaszdurka** [comment]
Retest this please.

**Comment by ppp0** [comment]
lgtm

**Comment by njam** [comment]
It looks like `monit.systemd.erb` is unused now and can be removed.

Also monit's `conf.d` is *not* purged with puppet (because we put entries from the application there). Either we should clean up production, or check if we can purge the directory now. Second one is probably better.

@tomaszdurka can you open a followup?

**Comment by tomaszdurka** [comment]
Done in #1523.

**Pull request merged**
