### PR TITLE
Spec rake tasks interrupted on invalid JSON output

### PR DESCRIPTION
**Pull request by tomaszdurka**
It seems like if a spec returns invalid JSON, the whole test run is interrupted, because of a parsing error.
We should make sure to continue the test run (and fail the specific spec)?

@tomaszdurka can you look into this?

```
/var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/formatters/json_formatter.rb:50:in `encode': "\xC2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/formatters/json_formatter.rb:50:in `to_json'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/formatters/json_formatter.rb:50:in `close'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:189:in `block in notify'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `each'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `notify'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:214:in `close'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:177:in `close_after'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:156:in `finish'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:79:in `report'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/bin/rspec:23:in `load'
	from /var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/bin/rspec:23:in `<main>'
rake aborted!
TypeError: can't convert nil into String
/var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/json_pure-1.8.3/lib/json/common.rb:155:in `initialize'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/json_pure-1.8.3/lib/json/common.rb:155:in `new'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/.bundle/vendor/ruby/1.9.1/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:86:in `initialize'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:176:in `new'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:176:in `run_spec_in_box'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:154:in `block (2 levels) in run'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:151:in `each'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:151:in `block in run'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:150:in `each'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/spec/lib/spec_runner.rb:150:in `run'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/Rakefile:29:in `execute'
/var/lib/jenkins/workspace/cargomedia-puppet-packages/Rakefile:40:in `block in <top (required)>'
```

### CODE REVIEW

**Comment by tomaszdurka** [comment]
After like whole day of back-and-forth I got this changeset. @njam @ppp0 wanna review?

**Comment by tomaszdurka** [comment]
I tried to run examples 1 by 1. First I would run `--dry-run --format json` to get all the examples. Later run each test again without dry-run.

I had some problems with performance though (ssh - grabbing vagrant options, then connecting itself - could not reuse it). Plus figured current way should be enough. Ofc it would be nice to see specific example which fails, but it might be not connected with the example at all in the end.

**Comment by njam** [comment]
- ExampleResult: add docus?
- run_spec_in_box: Instead of `(process_result.status === 0)` you could use `process_result.success?`
- run_spec_in_box: In rescue block: include `process_result.output` (instead of `.stdout`) in summary

**Comment by tomaszdurka** [comment]
Done, please check.

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
Could you also copy that to puppet-cargomedia then?

**Comment by tomaszdurka** [comment]
Yes.

**Pull request merged**
