### PR TITLE
Use janus-cluster-manager as npm package

### PR DESCRIPTION
**Pull request by tomaszdurka**
Depends on https://github.com/cargomedia/janus-cluster-manager/pull/14

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
CI failing because of https://github.com/cargomedia/janus-cluster-manager/pull/14 not being merged yet?

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
retest this please

**Comment by njam** [comment]
@tomaszdurka could you finish this up?

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
Fyi @njam @ppp0 finally merging, build passed.

**Comment by njam** [comment]
👍

**Pull request merged**
