### PR TITLE
Memcache: Make bind address configurable

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
paired w/ @kris-lab

**Comment by njam** [comment]
Ah config can also be removed?
https://github.com/cargomedia/puppet-packages/blob/master/modules/memcached/templates/memcached.conf

**Comment by kris-lab** [comment]
This config is still used with Wheezy?

**Comment by njam** [comment]
True!

**Comment by ppp0** [comment]
CI fails, waiting for https://github.com/cargomedia/puppet-packages/pull/1468

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
applied manually, works fine!

**Pull request merged**
