### PR TITLE
Refactor php-rdkafka module

### PR DESCRIPTION
**Pull request by tomaszdurka**
Added: https://github.com/cargomedia/puppet-packages/pull/1433
Once wheezy support for "php" is removed.

- Move everything to `php::extension::rdkafka`

cc @alexispeter

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by tomaszdurka** [comment]
@alexispeter wanna review?

**Comment by alexispeter** [comment]
Not sure what effect removing the puppetfile and metadata.json has. The rest looks good.

**Comment by njam** [comment]
Does this succeed on Debian 7? iirc we extracted this into a separate module to declare Debian 8-only compatibility. We could also remove Debian 7-support for the "php" module now!

**Comment by tomaszdurka** [comment]
Yes I thought it won't have support for Debian-7 and we should rather drop support in php5, wdyt?

**Comment by njam** [comment]
agree

**Comment by ppp0** [comment]
lgtm

**Comment by tomaszdurka** [comment]
so let's not wait on the build, I tested extension locally and worked fine

**Comment by tomaszdurka** [comment]
I need a /nod for that :)

**Comment by njam** [comment]
build is green, lgtm

**Pull request merged**
