### PR TITLE
[Upsource] Install missing libraries and upgrade to 2017.1

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review and merge if you like

**Comment by njam** [comment]
We are installing all of this, because our application that we configure in Upsource uses it. These are not direct dependencies of Upsource (include composer).
Could you move all of this to puppet-cargomedia, to make it installation specific?

**Comment by ppp0** [comment]
agree, will do!

**Comment by ppp0** [comment]
I slept over it and I now *partly* agree. Php and it's artefacts are not part of upsource but here due to our configuration. This is not the case for the missing `.so` shared binaries. So I leave them in this PR.
Copied from https://github.com/cargomedia/puppet-cargomedia/issues/1807#issuecomment-281386793
````
grep -i 'unsatisfied' /usr/local/jetbrains-upsource/logs/upsource-frontend/all.*
/usr/local/jetbrains-upsource/logs/upsource-frontend/all.log:java.lang.UnsatisfiedLinkError: /usr/local/jetbrains-upsource/internal/java/linux-x64/jre/lib/amd64/libjawt.so: libXext.so.6: cannot open shared object file: No such file or directory
/usr/local/jetbrains-upsource/logs/upsource-frontend/all.log:java.lang.UnsatisfiedLinkError: /usr/local/jetbrains-upsource/internal/java/linux-x64/jre/lib/amd64/libjawt.so: libXext.so.6: cannot open shared object file: No such file or directory
/usr/local/jetbrains-upsource/logs/upsource-frontend/all.log:java.lang.UnsatisfiedLinkError: /usr/local/jetbrains-upsource/internal/java/linux-x64/jre/lib/amd64/libjawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
/usr/local/jetbrains-upsource/logs/upsource-frontend/all.log.3:java.lang.UnsatisfiedLinkError: /usr/local/jetbrains-upsource/internal/java/linux-x64/jre/lib/amd64/libjawt.so: libXext.so.6: cannot open shared object file: No such file or directory
/usr/local/jetbrains-upsource/logs/upsource-frontend/all.log.5:java.lang.UnsatisfiedLinkError: /usr/local/jetbrains-upsource/internal/java/linux-x64/jre/lib/amd64/libjawt.so: libXext.so.6: cannot open shared object file: No such file or directory
/usr/local/jetbrains-upsource/logs/upsource-frontend/all.log.5:java.lang.UnsatisfiedLinkError: /usr/local/jetbrains-upsource/internal/java/linux-x64/jre/lib/amd64/libjawt.so: libXext.so.6: cannot open shared object file: No such file or directory
```

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by njam** [comment]
sgtm

- Puppetfile should be adjusted
- Manual upgrade needed!

**Comment by ppp0** [comment]
correct, thanks

**Comment by ppp0** [comment]
manual upgrade pending (as discussed in #infrastructure)

**Comment by kris-lab** [comment]
code looks good

**Comment by ppp0** [comment]
build fails for some Vagrant reasons (duplicate VBox..). Merging anyway

**Pull request merged**
