### PR TITLE
Don't install "latest" for gst plugins

### PR DESCRIPTION
**Pull request by kris-lab**
@kris-lab @ppp0 currently we install the "latest" gst plugin DEBs.

Should we change that, to have finer control over upgrades?

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by ppp0** [comment]
looks a bit weird to have a "present" version.. No way to default to `undef` and translate this later when `package { 'foo': ensure => present }` is called?

**Comment by kris-lab** [comment]
you can use `ensure` with value `present` or `installed` https://docs.puppet.com/puppet/3.8/reference/type.html#package-attribute-ensure

**Comment by njam** [comment]
imo we could just remove this "version" param, because the only values that can reasonably be passed are "present" and "latest" (but not any version string, and not "absend"). So I'd say it's rather confusing to have it in the first place.
wdyt?

**Comment by ppp0** [comment]
OK for me to completely remove it

**Comment by kris-lab** [comment]
@njam @ppp0 what about now?

**Comment by njam** [comment]
We usually specify `ensure => present`, but I guess it's optional.

retest this please

**Comment by ppp0** [comment]
it's not optional according to `lint`? Iirc we need to specify it.. or was it `provider => 'apt'`...

**Comment by ppp0** [comment]
retest this please

**Pull request merged**
