### PR TITLE
Manage journald's config file

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
part of https://github.com/cargomedia/puppet-cargomedia/issues/1771

**Comment by ppp0** [comment]
* OK
* Puppetfile already present? https://github.com/cargomedia/puppet-packages/blob/master/modules/systemd/Puppetfile

**Comment by kris-lab** [comment]
> Puppetfile already present?

of course, sorry

**Pull request merged**
