### PR TITLE
Daemon: Allow other signals than SIGTERM

### PR DESCRIPTION
**Pull request by ppp0**
Make stop signal configurable

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- systemd.service.erb: Why change [`Restart=`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) to "no"?

**Comment by ppp0** [comment]
To reflect the `force_stop` in a systemd environment (and thus make the spec test succeed)

**Comment by njam** [comment]
- Rename "forced_exit" to "sysvinit_kill"
- New test with TERM-ignoring program. Check for both cases (sysvinit and systemd) that process doesn't run anymore.

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm, could you enable it for fluentd?

**Pull request merged**
