### PR TITLE
Share cache log directory on Vagrantfile

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
This is needed to inspect (and store) the inner workings (logs) of the VM's proxy cache.
@kris-lab please review

**Comment by kris-lab** [comment]
Why we need to store these logs?

**Comment by ppp0** [comment]
The logs are otherwise stored (and disposed of) inside the VM  at every spec run. Impossible to debug like this

**Comment by kris-lab** [comment]
That's actually my question, is it needed only for current debugging or future wise?

**Comment by kris-lab** [comment]
code looks good, but I am not sure about value of this only?

**Comment by ppp0** [comment]
I noticed that a spec that *always* failed (on ci5), did not fail at several attempts after having enables the (shared) log. Also, I'd like to observer how well the cache is being hit or missed (first observations are not encouraging, ie high miss rate). Can't we remove it a later stage if we have overcome the caching problem?

**Comment by kris-lab** [comment]
ok!

**Pull request merged**
