### PR TITLE
Reimplement RAID checks

### PR DESCRIPTION
**Pull request by ppp0**
- Don't use the wrapper scripts from "hwraid" anymore.
- Use the vendor binaries for each RAID controller, installable from https://github.com/cargomedia/debian-packages/:
 - arcconf
 - storcli (previously MegaCLI)
 - sas2ircu
 - hpacucli
- Check health with a simple `cli-command | grep "Optimal"` (or a wrapper perl, bash script), and run it regularly from monit:
```
CHECK PROGRAM bar PATH /bin/true
 IF STATUS != 0 THEN ALERT
```

cc @kris-lab @ppp0

### CODE REVIEW

**Comment by njam** [comment]
- Use facts.json
- mdadm: let's stick to the original daemon/check (`/etc/mdadm.conf`)

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
@njam now all specs succeed, please final check

**Comment by njam** [comment]
lgtm!

Let's merge, release carefully, and then enable for ubuntu (see https://github.com/cargomedia/puppet-cargomedia/blob/master/modules/cargomedia_base/manifests/init.pp#L29)

**Comment by ppp0** [comment]
OK, after applying #1130 it seems all good everywhere. Corss-checked monit status vs. actual RAID status and hardware..

**Comment by ppp0** [comment]
hpaucli missing! (Done in #1131)

**Pull request merged**
