### PR TITLE
[RAID monitoring] Add missing sas2ircu script

### PR DESCRIPTION
**Pull request by ppp0**
Follow-up of https://github.com/cargomedia/puppet-packages/pull/1065

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by ppp0** [comment]
Another bug :/ - LSI monitoring does not work (affected: backup1)

**Comment by ppp0** [comment]
Also check `sk-reflected` when done

**Comment by njam** [comment]
- sas2ircu.pp: `File['/usr/local/sbin/sas2ircu-status']` probably requires the binary, so the package?
- specs are failing (exit code 3?)

**Comment by ppp0** [comment]
* We're dumping the package from le vert - this is a python script? (https://github.com/ppp0/puppet-packages/blob/issue-1130/modules/raid/templates/sas2ircu/sas2ircu-status) and monit needs it to correctly check the status?
* Specs failing: on it

**Comment by njam** [comment]
I meant "requiring" as int `requires => some other resource`.

**Pull request merged**
