### PR TITLE
[RAID] - Add hpssacli

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
To be verified (on bulldog2) that problems with the RAID actually really lead to an error. Just pull a drive out of bulldog2 and see what happens

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by ppp0** [comment]
>To be verified (on bulldog2) that problems with the RAID actually really lead to an error. Just pull a drive out of bulldog2 and see what happens

:cry: 

```sh
hpssacli -exitonerror controller all show config;echo $?

Smart Array P440ar in Slot 0 (Embedded)   (sn: PDNLH0BRH9B1YO)


   Port Name: 1I

   Port Name: 2I

   Internal Drive Cage at Port 1I, Box 6, OK

   Internal Drive Cage at Port 2I, Box 0, OK
   array A (Solid State SATA, Unused Space: 0  MB)


      logicaldrive 1 (111.8 GB, RAID 1, Interim Recovery Mode)

      physicaldrive 1I:6:1 (port 1I:box 6:bay 1, Solid State SATA, 120 GB, Failed)
      physicaldrive 1I:6:2 (port 1I:box 6:bay 2, Solid State SATA, 120 GB, OK)

0
```

WTF WTF

**Pull request merged**
