### PR TITLE
Reduce nginx proxy read timeout for socket-redis vhost

### PR DESCRIPTION
**Pull request by njam**
Addressing #1368

### CODE REVIEW

**Comment by njam** [comment]
@vogdb please review

**Comment by vogdb** [comment]
lgtm

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
Failing specs are unrelated. Nodejs fails to install:
```
      E: Failed to fetch https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/nodejs_5.12.0-1nodesource1~jessie1_amd64.deb  GnuTLS recv error (-9): A TLS packet with unexpected length was received.
```
Cannot reproduce locally. Probably a polipo issue.

**Pull request merged**
