### PR TITLE
Remove phpmyadmin

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
please check specs

**Comment by ppp0** [comment]
I don't get this.. 
```
[...]
==> Debian-8: Checking for updates to 'cargomedia/debian-8-amd64-default'
    Debian-8: Latest installed version: 0.1.0
    Debian-8: Version constraints: 
    Debian-8: Provider: virtualbox
==> Debian-8: Box 'cargomedia/debian-8-amd64-default' (v0.1.0) is running the latest version.
From ssh://github.com/cargomedia/puppet-packages
   74a9fac..a2ca864  master     -> origin/master
rake aborted!
Module phpmyadmin not found
/var/lib/jenkins/workspace/cargomedia-puppet-packages-pr/spec/lib/finder.rb:64:in `puppet_module'
/var/lib/jenkins/workspace/cargomedia-puppet-packages-pr/Rakefile:71:in `block (3 levels) in <top (required)>'
/var/lib/jenkins/workspace/cargomedia-puppet-packages-pr/Rakefile:70:in `map'
/var/lib/jenkins/workspace/cargomedia-puppet-packages-pr/Rakefile:70:in `block (2 levels) in <top (required)>'
Tasks: TOP => spec:changes_from_branch
(See full trace by running task with --trace)
vagrant halt --force
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

of course, `Module phpmyadmin not found` - I deleted it in this PR

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
Probably a bug - looks for changed files, and runs the appropriate specs.
Can you look into it?

**Comment by ppp0** [comment]
Opened https://github.com/cargomedia/puppet-packages/issues/1188

does the PR look good?

**Comment by njam** [comment]
lgtm

**Pull request merged**
