### PR TITLE
Add fluentd module

### PR DESCRIPTION
**Pull request by njam**
For now it's just the basics from today's workshop (https://www.crowdcast.io/e/fluentd).

Will add some more resources (sources, matches?) to make it usable.

### CODE REVIEW

**Comment by njam** [comment]
One strange issue remains, where the fluentd process doesn't exit on SIGTERM.
Possibly related to https://github.com/fluent/fluentd/issues/672

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
@ppp0 @kris-lab please review

@tomaszdurka fyi

**Comment by njam** [comment]
@ppp0 @kris-lab please review

**Comment by kris-lab** [comment]
Looks very good to me!

**Comment by ppp0** [comment]
lgtm, too

**Pull request merged**
