### PR TITLE
Upgrade cm-janus (without job handlers)

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
`handlersConfiguration: {}` is this `{}` really needed?

**Comment by tomaszdurka** [comment]
Yep.

**Comment by tomaszdurka** [comment]
This is temporary. I just don't wanna merge jobs config until we have resolved fully jobs issue.

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
