### PR TITLE
SYS-183 Add fluentd::source_logfile to parse file-based mysql logs

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
to be discussed:
* unit name.. mysql everwhere and select based on other criteria (e.g. logfile, transport)
* match the error level which is now embedded in message (and has levels error, warning and note)

**Comment by ppp0** [comment]
Check permission problems on /var/log/mysql.err (looks like the deb install is overriding our settings)

**Comment by ppp0** [comment]
Looks like using a file name other than `/var/log/mysql.err` is solving the problem. Looks like mysql is forcibly chmod'ing the file

**Comment by zazabe** [comment]
looks good, but let's wait for SYS-204, seems source_logfile is producing empty logs ...
also, be carful about the impact of these changes in prod :)

**Comment by ppp0** [comment]
Needs application downtime (ca 2 min) to deploy:

* Stop puppet 
`CERTNAMEFILTER=db-master1.cargomedia.net,db-slave3.cargomedia.net,db-slave4.cargomedia.net,gearman2.cargomedia.net pulsar invoke COMMAND='sudo systemctl stop puppet'`
* merge
* `pulsar sk production deploy:stop`
* Apply `CERTNAMEFILTER=db-slave3.cargomedia.net,db-slave4.cargomedia.net,gearman2.cargomedia.net pulsar puppet:onetime`
* Apply `CERTNAMEFILTER=db-master1.cargomedia.net pulsar puppet:onetime`
* `pulsar sk production deploy:start`
* `CERTNAMEFILTER=db-master1.cargomedia.net,db-slave3.cargomedia.net,db-slave4.cargomedia.net,gearman2.cargomedia.net pulsar invoke COMMAND='sudo systemctl stop puppet'`

**Pull request merged**
