### PR TITLE
Janus: add bipbip/logparser for missing key-frames detection

### PR DESCRIPTION
**Pull request by kris-lab**
```
[ERR] [libjanus_rtpbroadcast.c:cm_rtpbcast_relay_thread:2270] [Ababagalamaga] Key frame overdue on source 3
[ERR] [libjanus_rtpbroadcast.c:cm_rtpbcast_relay_thread:2270] [Ababagalamaga] Key frame overdue on source 1
[ERR] [libjanus_rtpbroadcast.c:cm_rtpbcast_relay_thread:2270] [Ababagalamaga] Key frame overdue on source 2
[ERR] [libjanus_rtpbroadcast.c:cm_rtpbcast_relay_thread:2262] [Ababagalamaga] Key frame arriveed 200 frames late on source 3
[ERR] [libjanus_rtpbroadcast.c:cm_rtpbcast_relay_thread:2262] [Ababagalamaga] Key frame arriveed 200 frames late on source 1
[ERR] [libjanus_rtpbroadcast.c:cm_rtpbcast_relay_thread:2262] [Ababagalamaga] Key frame arriveed 200 frames late on source 2
```

https://github.com/cargomedia/janus-gateway-rtpbroadcast/blob/master/libjanus_rtpbroadcast.c#L2261

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look. This metrics should basically go to the `plugin/rtpbroadcast` class. However it requires log path so I decided to leave it in janus itself. wdyt?

**Comment by njam** [comment]
How about moving it to the rtpbroadcast plugin, and accessing the log file location from `janus`?
```
$ puppet apply -e 'class foo($my=12) { notify{"my=${my}":} } class bar { notify{"foo::my=${foo::my}":} } class{"foo":my=>13} class{"bar":}'
Please report a bug if this causes problems.
Notice: Compiled catalog for owl.local in environment production in 0.06 seconds
Notice: my=13
Notice: /Stage[main]/Foo/Notify[my=13]/message: defined 'message' as 'my=13'
Notice: foo::my=13
Notice: /Stage[main]/Bar/Notify[foo::my=13]/message: defined 'message' as 'foo::my=13'
Notice: Applied catalog in 0.01 seconds
```

**Comment by kris-lab** [comment]
This is exactly what we discuss regarding `UFW` and we tried to avoid... accessing default values of classes? If you think it's fine I can re-factor.

**Comment by njam** [comment]
What was the use case for UFW? I think we should *never* do it cross-module, to reduce dependencies between modules. But within a module I think it's okay. wdyt?

**Comment by kris-lab** [comment]
This is what I am not sure... is this cross-module params sharing ok? Agree it makes things easier.

Will re-factor then...

**Comment by njam** [comment]
I think we should not do it cross-module. But here it's the same module, different class, right? `janus` and `janus::plugin::rtpbroadcast`. I think for that it's fine.

**Comment by kris-lab** [comment]
@njam please have a look. tested manually, works fine

**Comment by kris-lab** [comment]
retest this please

**Comment by njam** [comment]
Tests failing because of custom ffmpeg packages which are not finished yet.
@ppp0 will un-release them, then we can re-test.

**Comment by njam** [comment]
retest this please

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
reverted `ffmpeg` https://github.com/cargomedia/debian-packages/pull/91

**Comment by kris-lab** [comment]
retest this please

**Comment by kris-lab** [comment]
@njam are you ok to merge this? Build failures is not related.

**Comment by njam** [comment]
Agree, not related.

But let's get the build working. Was it bad timing, when Philipp was syncing the repo? Is it okay now?

retest this please

**Comment by kris-lab** [comment]
retest this please

**Pull request merged**
