### PR TITLE
add phantomjs to puppetfile

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@zazabe please review

**Comment by tomaszdurka** [comment]
lgtm

**Comment by tomaszdurka** [comment]
I still get:

```
==> default: Error: 
==> default: mkdir -p /tmp/b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: cd /tmp/b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: echo \#\!/bin/bash\ -e'
==> default: ''
==> default: 'PHANTOMJS\=\'phantomjs-2.1.1-linux-x86_64\''
==> default: 'curl\ -L\ https://bitbucket.org/ariya/phantomjs/downloads/\$\{PHANTOMJS\}.tar.bz2\ \>\ \$\{PHANTOMJS\}'
==> default: 'tar\ xjf\ \$\{PHANTOMJS\}'
==> default: 'mv\ \$\{PHANTOMJS\}\ phantomjs'
==> default: 'rm\ -rf\ /usr/local/share/phantomjs'
==> default: 'mv\ phantomjs\ /usr/local/share/'
==> default: ' > b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: chmod +x b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: ./b7ce7b8912c15aec9426c6632b40fe59 returned 6 instead of one of [0]
==> default: Error: /Stage[main]/Phantomjs/Helper::Script[install phantomjs]/Exec[exec install phantomjs]/returns: change from notrun to 0 failed: 
==> default: mkdir -p /tmp/b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: cd /tmp/b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: echo \#\!/bin/bash\ -e'
==> default: ''
==> default: 'PHANTOMJS\=\'phantomjs-2.1.1-linux-x86_64\''
==> default: 'curl\ -L\ https://bitbucket.org/ariya/phantomjs/downloads/\$\{PHANTOMJS\}.tar.bz2\ \>\ \$\{PHANTOMJS\}'
==> default: 'tar\ xjf\ \$\{PHANTOMJS\}'
==> default: 'mv\ \$\{PHANTOMJS\}\ phantomjs'
==> default: 'rm\ -rf\ /usr/local/share/phantomjs'
==> default: 'mv\ phantomjs\ /usr/local/share/'
==> default: ' > b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: chmod +x b7ce7b8912c15aec9426c6632b40fe59 && \
==> default: ./b7ce7b8912c15aec9426c6632b40fe59 returned 6 instead of one of [0]
```

@zazabe @njam @ppp0 ?

**Comment by tomaszdurka** [comment]
Merging the Puppetfile pr.

**Comment by tomaszdurka** [comment]
This was my network issues.

**Pull request merged**
