### PR TITLE
Use Komenda to run shell commands

### PR DESCRIPTION
**Pull request by njam**
Addressing #1496

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab @ppp0 please review

this fixes https://github.com/cargomedia/puppet-packages/issues/1496, because Komenda has some extra logic built in to ignore any Bundler environment when spawning programs.

**Comment by njam** [comment]
Closes #1496

**Comment by kris-lab** [comment]
ok, sgtm, lgtm

**Comment by ppp0** [comment]
lgtm, too!

**Pull request merged**
