### PR TITLE
[nginx] - Make server_names_hash_bucket_size configurable

### PR DESCRIPTION
**Pull request by ppp0**
On a virtual node it seems nginx has problems detecting the proper CPU cache line size (see https://trac.nginx.org/nginx/ticket/352)

If virtual hostnames become too long, you'll get the error
```
[emerg] 13253#0: could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32
```

(This on a virtual node that has `getconf LEVEL1_DCACHE_LINESIZE == 64`)

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- What's the reasoning for  1daf6b5? `hasrestart` does *not* default to `true`. I think `enable` might also be needed?

rest lgtm

**Comment by ppp0** [comment]
OK, reverted

**Comment by njam** [comment]
Where was it reverted?

**Comment by ppp0** [comment]
Oh, I did not push :blush:

**Pull request merged**
