### PR TITLE
Run apt-get update if local package cache older than x

### PR DESCRIPTION
**Pull request by kris-lab**
Following the discussion in #837 

To be confirmed if it is a viable solution

e.g. (ruby)
```rb
 (Time.now - File.stat('/var/cache/apt').mtime).to_i / 86400.0
```
returns the age of the directory in days as `float` 

refresh every day?

### CODE REVIEW

**Comment by njam** [comment]
Also now we could require `apt::update` when installing any package with apt?
Maybe also check usages of `apt::update`, I remember we did some quirky things there to make sure the index is up to date in the right moment..

**Comment by kris-lab** [comment]
afaics we require `apt update` with `exec` for each `package` now?

**Comment by njam** [comment]
Makes sense, as soon as we either include `apt::update` or `apt`. Which we do in `cargomedia::base`.
But we don't do it in puppet-packages tests?

Looking at the code I would
- Use seconds for age (SI unit), or make it clear it's days

**Comment by kris-lab** [comment]
@ppp0 @njam could you have a look on spec?

The problem is that `apt::update` running command `apt-get -o Acquire::http::proxy=false update` is not updating modification timestamp for `/var/cache/apt`. If I run it manually in the box then all is fine. If puppet runs this command then it is done but time of access/modification is not updated?

**Comment by njam** [comment]
Try this approach?
http://serverfault.com/questions/20747/find-last-time-update-was-performed-with-apt-get/425237#425237

**Comment by kris-lab** [comment]
Still the same problem!

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
renaming as discussed, rest looks good

**Comment by ppp0** [comment]
very good job!

**Pull request merged**
