### PR TITLE
Upgrade Node.js to v5.x

### PR DESCRIPTION
**Pull request by njam**
From 0.12

Used by:
- autoprefixer
- bower
- browserify
- cm-janus
- less
- pulsar-rest-api
- socket-redis
- uglify

@vogdb fyi

### CODE REVIEW

**Comment by njam** [comment]
@vogdb please review

I ran the specs of all affected modules (see above). I checked cm-janus specifically. inode is working, it picks up new job definitions as they appear on the filesystem.

**Comment by njam** [comment]
@ppp0 or you want to review?
btw also making Node.js available for Debian 8 here.

**Comment by vogdb** [comment]
Why did you put here the upgrade of debian to 8?

**Comment by njam** [comment]
Nope, just making the Node.js module compatible with Debian 8.

@vogdb @ppp0 good to go?

**Comment by vogdb** [comment]
lgtm from me

**Pull request merged**
