### PR TITLE
Use a fact "bootstrap" for bootstrapping puppet

### LINKED ISSUE #721: Fix puppet provision step
Tag-based provisioning doesn't work reliably, because no dependencies are resolved.
Usage in [pulsar-conf-cargomedia's puppet.rb](https://github.com/cargomedia/pulsar-conf-cargomedia/blob/master/recipes/puppet/puppet.rb#L16).
@kris-lab @ppp0 can you look into this? cc @tomaszdurka 

Idea:
Using (directory) environments, then selecting a *special* environment `provisioning` for the first run.
https://docs.puppetlabs.com/puppet/latest/reference/environments.html
https://docs.puppetlabs.com/puppet/latest/reference/environments_assigning.html
https://docs.puppetlabs.com/puppet/latest/reference/environments_creating.html

But can we easily reuse all modules for the new environment?

### PR DESCRIPTION
**Pull request by njam**
Paired with @kris-lab
Closes #721

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab please double check

**Comment by kris-lab** [comment]
lgtm

**Comment by njam** [comment]
@tomaszdurka @ppp0 fyi

**Comment by tomaszdurka** [comment]
Looks good. Makes more sense. Did you think about rather doing bootstrap when no `bootstrapped` fact? We could add this fact after bootstrapping. Current allows bootstrapping multiple times - plus?

**Comment by njam** [comment]
Could be as well! Doesn't make much of a difference imo.

**Pull request merged**
