### PR TITLE
Apt source changes

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
* Make apt::source::cargomedia work with Ubuntu (and Debian 8) -> explicit architecture in source (see https://wiki.debian.org/Multiarch/HOWTO for reference)
* Move dotdeb into separate, Debian7 only module
* Adapt usages and specs

@njam please review

@kris-lab @dergraf fyi

**Comment by njam** [comment]
@tomaszdurka @kris-lab please review

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
this requires destroy of machine?

**Comment by ppp0** [comment]
sounds weird, why should it? Works for me on local vm... investigating

**Comment by njam** [comment]
Machine name has changed (1504 -> 15.04) - please merge upstream and adjust usages

**Comment by ppp0** [comment]
who's up for a quick review? @tomaszdurka ? @kris-lab ?

**Comment by kris-lab** [comment]
hmm afaics lgtm

**Pull request merged**
