### PR TITLE
Service on template does not match variable

### PR DESCRIPTION
**Pull request by tomaszdurka**
Variable from template:
- https://github.com/cargomedia/puppet-packages/blob/master/modules/raid/templates/linux_md/monit.systemd.erb#L1

doesn't match one from manifest: 
- https://github.com/cargomedia/puppet-packages/blob/master/modules/raid/manifests/linux_md.pp#L6

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
the correct spelling is `mdadm` (adm being admin), so may be change this where the variable gets set?

**Comment by ppp0** [comment]
@tomaszdurka fyi

**Comment by tomaszdurka** [comment]
lgtm

**Pull request merged**
