### PR TITLE
Remove redis php extension

### PR DESCRIPTION
**Pull request by zazabe**
Switched to predis lib instead, see cargomedia/cm#1923

### CODE REVIEW

**Comment by zazabe** [comment]
@njam please review

**Comment by njam** [comment]
lgtm, but merge this only 1-2 weeks after we did the change

**Comment by zazabe** [comment]
@njam could we merge it? 
Anyhow, I don't think that puppet will actually remove the extension, isn't it?

**Comment by njam** [comment]
It will not remove it. But I would like to wait until I've upgraded CM in https://github.com/denkmal/denkmal.org/ - otherwise new installs will fail there.

**Pull request merged**
