### PR TITLE
Deadlock when installing redis-server

### PR DESCRIPTION
**Pull request by ppp0**
On both wheezy and jessie, puppet gets stuck when `apt-get install`ing redis-server. On CI as well (when running spec tests)

Strangely, we did not experience this before. Does it relate to the `daemon` module being used?

If I ssh into the box and `ps ax` I get

```
[..]
9181 ?        Ss     0:00 /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install redis-server
 9430 ?        S      0:00 /usr/bin/dpkg --force-confold --status-fd 30 --configure redis-server:amd64
 9431 ?        S      0:00 /bin/sh /var/lib/dpkg/info/redis-server.postinst configure 
 9436 ?        S      0:00 /bin/sh /usr/sbin/invoke-rc.d redis-server start
 9453 ?        S      0:00 /bin/sh /etc/init.d/redis-server start
 9458 ?        Sl     0:00 /usr/bin/redis-server /etc/redis/redis.conf
[..]
```

Looks like install is not yet over (proc 9431) yet the service has already been started...

If I send SIGTERM to 9431, puppet exits with
```
[..]
Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n' redis-server'
Debug: Executing '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install redis-server'
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install redis-server' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  redis-server
0 upgraded, 1 newly installed, 0 to remove and 43 not upgraded.
Need to get 235 kB of archives.
After this operation, 582 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian/ wheezy/main redis-server amd64 2:2.4.14-1 [235 kB]
Fetched 235 kB in 0s (0 B/s)
Selecting previously unselected package redis-server.
(Reading database ... 52480 files and directories currently installed.)
Unpacking redis-server (from .../redis-server_2%3a2.4.14-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up redis-server (2:2.4.14-1) ...

Configuration file `/etc/redis/redis.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
Starting redis-server: dpkg: error processing redis-server (--configure):
 subprocess installed post-installation script was killed by signal (Terminated)
Errors were encountered while processing:
 redis-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
[..]
```

The configure process somehow is flawed..

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
@njam please review

The hack is to temporarily write an init script which will do nothing. After package installation, daemon will re-install and restart the service

**Comment by kris-lab** [comment]
I assume there is no logic with `/etc/default/redis-server` which would prevent this start?

**Comment by ppp0** [comment]
I haven't found any and under `systemd` it wouldn't be evaluated either

**Comment by kris-lab** [comment]
We also know the service name, yes? Could it be stopped with puppet service resource?

**Comment by njam** [comment]
- Replace all the `->`? Other ways of ordering resources are more flexible
- Config file: notify daemon
- Sysctl entry: notify daemon

**Comment by ppp0** [comment]
The problem is a run condition which arises at `apt-get install` time. The deb's postinstall script wants to start the service and this can't be done for reasons unknown to me. Consequently, puppet hangs at `package ensure=>present`

**Comment by ppp0** [comment]
exceprt from puppet's debug trace:
```
Notice: /Stage[main]/Redis/Sysctl::Entry[redis]/File[/etc/sysctl.d/redis]/ensure: defined content as '{md5}13eb83462f9999cc2b319c9ca3fe6fcf'
Notice: /Stage[main]/Redis/Sysctl::Entry[redis]/Exec[/sbin/sysctl -p /etc/sysctl.d/redis]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Redis/File[/etc/init.d/redis-server]/ensure: defined content as '{md5}df0b969ca5bd465a8a8bb946b83e520d'
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install redis-server' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libjemalloc1 redis-tools
The following NEW packages will be installed:
  libjemalloc1 redis-server redis-tools
0 upgraded, 3 newly installed, 0 to remove and 3 not upgraded.
Need to get 476 kB of archives.
After this operation, 1285 kB of additional disk space will be used.
Get:1 http://httpredir.debian.org/debian/ jessie/main libjemalloc1 amd64 3.6.0-3 [89.1 kB]
Get:2 http://httpredir.debian.org/debian/ jessie/main redis-tools amd64 2:2.8.17-1+deb8u3 [79.3 kB]
Get:3 http://httpredir.debian.org/debian/ jessie/main redis-server amd64 2:2.8.17-1+deb8u3 [308 kB]
Fetched 476 kB in 0s (11.9 MB/s)
Selecting previously unselected package libjemalloc1.
(Reading database ... 41172 files and directories currently installed.)
Preparing to unpack .../libjemalloc1_3.6.0-3_amd64.deb ...
Unpacking libjemalloc1 (3.6.0-3) ...
Selecting previously unselected package redis-tools.
Preparing to unpack .../redis-tools_2%3a2.8.17-1+deb8u3_amd64.deb ...
Unpacking redis-tools (2:2.8.17-1+deb8u3) ...
Selecting previously unselected package redis-server.
Preparing to unpack .../redis-server_2%3a2.8.17-1+deb8u3_amd64.deb ...
Unpacking redis-server (2:2.8.17-1+deb8u3) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u4) ...
Setting up libjemalloc1 (3.6.0-3) ...
Setting up redis-tools (2:2.8.17-1+deb8u3) ...
Setting up redis-server (2:2.8.17-1+deb8u3) ...

Configuration file '/etc/init.d/redis-server'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.

Configuration file '/etc/redis/redis.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
adduser: Warning: The home directory `/var/lib/redis' does not belong to the user you are currently creating.
insserv: warning: script 'redis-server' missing LSB tags and overrides
insserv: There is a loop between service monit and redis-server if stopped
insserv:  loop involving service redis-server at depth 2
insserv:  loop involving service monit at depth 1
insserv: Stopping redis-server depends on monit and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package redis-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Errors were encountered while processing:
 redis-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

inside the box, there were hanging `dpkg -i` processes and a running `redis-server`... I don't have the screendumps anymore. @kris-lab fyi

I believe the change has to do with the introduction of our `daemon` module and that we start `redis` in the foreground instead of the standard forking (aka daemonized).

**Comment by ppp0** [comment]
@njam please review

**Comment by kris-lab** [comment]
You said it hangs yes? But, what is this:
````
...
insserv: Stopping redis-server depends on monit and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package redis-server (--configure)
...
```

**Comment by ppp0** [comment]
This is about the init script header, e.g.
```
# Required-Start:     $local_fs $syslog
# Required-Stop:      $local_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
```

our version (via https://github.com/cargomedia/puppet-packages/blob/master/modules/daemon/templates/sysvinit.sh.erb#L3) looks like this:
```
### BEGIN INIT INFO
# Provides:           <%= @name %>
# Required-Start:     $local_fs $syslog
# Required-Stop:      $local_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  <%= @name %>
### END INIT INFO
```

**Comment by ppp0** [comment]
may be we should have a closer look at https://github.com/cargomedia/puppet-packages/blob/master/modules/monit/templates/init#L7

**Comment by kris-lab** [comment]
Agree it complains about `$all`. However I do see any solution. If killing the process works then good for me.

**Comment by njam** [comment]
btw this workaround is only for sysvinit - so for systemd this is not an issue?

**Comment by ppp0** [comment]
Afraid to say that it equally affected both sysvinit and systemd, which is why I don't think it is a particular issue with the init script - I might be mistaken, though

**Comment by ppp0** [comment]
#### debian/postint

##### systemd
```
#!/bin/sh

set -eu

USER="redis"
GROUP="$USER"

case "${1}" in
	configure)
		adduser \
			--home /var/lib/redis \
			--quiet \
			--system \
			--group \
			${USER}

		for DIR in /var/lib/redis /var/log/redis
		do
			mkdir -p ${DIR}
			chown -R ${USER}:${GROUP} ${DIR}
		done
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask redis-server.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled redis-server.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable redis-server.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state redis-server.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
# In case this system is running systemd, we need to ensure that all
# necessary tmpfiles (if any) are created before starting.
if [ -d /run/systemd/system ] ; then
	systemd-tmpfiles --create /usr/lib/tmpfiles.d/redis-server.conf >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/redis-server" ]; then
	update-rc.d redis-server defaults >/dev/null
	invoke-rc.d redis-server start || exit $?
fi
# End automatically added section


exit 0
```

##### sysvinit

```
#!/bin/sh

set -eu

USER="redis"
GROUP="$USER"

chown $USER:$GROUP /var/lib/redis
chown $USER:$GROUP /var/log/redis

# Automatically added by dh_installinit
if [ -x "/etc/init.d/redis-server" ]; then
	update-rc.d redis-server defaults >/dev/null
	invoke-rc.d redis-server start || exit $?
fi
# End automatically added section
```

**Comment by ppp0** [comment]
I tried something different no:
* no config from our side
* install package
* stop service
* apply our config
* restart non-daemonized with our daemon module

**Comment by njam** [comment]
Agree on the approach in general.
BTW did you consider using the package's daemon scripts? Is there a reason not to use them?

`/etc/init.d/redis-server stop` is sysvinit specific. You could try `service redis-server stop` instead?

**Comment by ppp0** [comment]
Let's look at it tomorrow I'm not been successful so far, really

Yes, I looked into the deb's service definition.. It's from type=forking and presumes a daemonizing server. There is also a execstop script. I thought we better streamline

```
[Unit]
Description=Advanced key-value store
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/redis-server /etc/redis/redis.conf
ExecStop=/usr/bin/redis-cli shutdown
Restart=always
User=redis
Group=redis

[Install]
WantedBy=multi-user.target
```


You are partly right in that `/etc/init.d/foo stop` stems from sysvinit. Under systemd though, the scripts are still there and when invoked, the call gets seamlessly translated into a `systemctl` action. See the first paragraphs of [this text](https://www.turnkeylinux.org/blog/debugging-systemd-sysv-init-compat).

**Comment by njam** [comment]
Ok I see. If it works fine and we can skip all this hassle, I would suggest to use the package's original service scripts.

**Comment by ppp0** [comment]
a major pain has gone.. redis does not seem to like to be run undaemonized

**Comment by ppp0** [comment]
@njam please review - specs succeed locally at least

**Comment by njam** [comment]
lgtm

@kris-lab can you double check? Once it's fine let's merge it. I'm running into this bug many times locally…

**Comment by ppp0** [comment]
feel free to merge when double checked as I'm away until Tuesday

**Comment by kris-lab** [comment]
I did only basic tests, but all worked for me.

lgtm

**Comment by njam** [comment]
Ok, deployed to production manually.

Let's take this as a reminder to not merge and release changes that don't have a green build and/or have known problems.

**Pull request merged**
