### PR TITLE
Run "apt update" before every spec

### PR DESCRIPTION
**Pull request by njam**
..to make sure apt's index is up-to-date.

This adds 2.5secs for every test.

@ppp0 @tomaszdurka wdyt?

### CODE REVIEW

**Comment by ppp0** [comment]
I reckon there is no other way.. sounds a bit redundant - placing the apt cache on a shared folder (`/vagrant/spec/apt/`)could be an option?

Looking at the code changes I'm not sure it this issue's title completely reflects what you are doing

**Comment by njam** [comment]
Yup, I've also changed the puppet run to use `--detailed-exitcodes`.

I'd suggest to merge this version for now to avoid failing builds, and look into the shared folder option later as an optimization.
wdyt?

**Comment by ppp0** [comment]
sgtm, lgtm

**Comment by njam** [comment]
@tomaszdurka wanna have a look too?

**Comment by tomaszdurka** [comment]
Are you sure that `--detailed-exitcodes` will make puppet command fail on puppet resources failures? I remember that regexp search was added on purpose. If catalog was compiled fine command always returned 0 no matter if there were some puppet errors during apply.

**Comment by njam** [comment]
I had something like that in mind too, but couldn't confirm.
Now I think I remember: If the catalog compilation fails it didn't error? I will test this...

**Comment by tomaszdurka** [comment]
If remember correctly puppet apply exit code is related only to compilation of the catalog, but not with realization of the compiled resources.

- It will return non-zero code on syntax errors, infinite dependency loops, etc.
- It will return zero code on resource realization errors.

**Comment by njam** [comment]
Can't confirm (anymore): Errors during compilation and during applying both lead to non-0 exit code.
```
# puppet apply -e 'package {"dshfihn":}' --detailed-exitcodes; echo $?
Notice: Compiled catalog for debian-7-amd64-default.vagrantup.com in environment production in 0.11 seconds
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install dshfihn' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dshfihn
Error: /Stage[main]/Main/Package[dshfihn]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install dshfihn' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dshfihn
Notice: Finished catalog run in 0.25 seconds
4
```

Agree to merge then?

**Comment by tomaszdurka** [comment]
Sure. I would keep a closer look on specs for some time.

**Pull request merged**
