### PR TITLE
Enable bipbip log rotation

### PR DESCRIPTION
**Pull request by njam**
This reverts commit d2e7b3eb703ac46656e4ac38e95fcd92e3c96b05, reversing
changes made to fc725df2c8ce8e16e0597b51736bf4a18f644746.

### CODE REVIEW

**Comment by ppp0** [comment]
lgtm, waiting for spec tests

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
Virtualbox problems..

retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
Hmm build failing because bipbip doesn't start.
Can't reproduce locally..

retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
Hmmm again:
```
       Stderr: VBoxManage: error: UUID {87f385af-a5ba-4e49-9ad8-7f0020815ed7} of the medium '/var/lib/jenkins/workspace/cargomedia-puppet-packages-pr/.vagrant/machines/wheezy/virtualbox/hard-disks/additional_disk.vdi' does not match the value {dff76e0b-8868-4b77-adea-a61bc7c5b18d} stored in the media registry ('/var/lib/jenkins/.config/VirtualBox/VirtualBox.xml')
```
destroying box...

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
@ppp0 please review last two commits

**Comment by ppp0** [comment]
lgtm

**Pull request merged**
