### PR TITLE
Add "after" and "before" parameter to daemon

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

Ideas on how to 100% make sure that the dependency is honoured by `systemd` and not by puppet?

**Comment by kris-lab** [comment]
- modules/daemon/manifests/init.pp: has the `$after` to be default?

I don'y fully understand what we test in the spec:) could you explain a bit?

**Comment by ppp0** [comment]
As discussed with @njam, let's introduce `before`, too..

The tests:
* foo service executes a one-shot program which in turn creates a file in `/tmp`
* my-program "daemon" expects the file to be there to run in a loop

**Comment by kris-lab** [comment]
- `before` sounds good!
- test: ok, I agree

**Comment by njam** [comment]
For the records - as discussed yesterday: Systemd's ordering instructions (Before/After) apply to when starting multiple units at the same time. So for example at boot. I think it will be difficult to test that in a acceptance spec, I also think it might not be necessary.

**Comment by ppp0** [comment]
@kris-lab @njam anyone up for a review?

**Comment by kris-lab** [comment]
@ppp0 quick question: did we decide to ignore before/after configuration on the `sysvinit`? Maybe we should make it more clear?

**Comment by ppp0** [comment]
We had a look at https://wiki.debian.org/LSBInitScripts on how to do this in init scripts. Unfortunately, there is some sort of `after` (defining which service has to be started before, see `X-Start-Before` and `should-start`) but not `before`.

While it would be nice to have a puppet define that abstracts from the init system, we discussed that it's too much of an effort given that we're going to phase out Wheezy in the near future

I can make a comment in the code

**Comment by kris-lab** [comment]
As discussed let's close this thread. It does not solve the problem.

closing in favor of https://github.com/cargomedia/puppet-packages/issues/1359

**Pull request closed without merging**
