### PR TITLE
Add php SPL_Types extension

### PR DESCRIPTION
**Pull request by njam**
@fvovan wdyt?

### CODE REVIEW

**Comment by fvovan** [comment]
my only concern is 
>Warning
This extension is EXPERIMENTAL. The behaviour of this extension including the names of its functions and any other documentation surrounding this extension may change without notice in a future release of PHP. This extension should be used at your own risk.

http://php.net/manual/en/intro.spl-types.php

**Comment by njam** [comment]
I would still give it a shot. Quite unlikely that they will change it  / drop it completely?
Otherwise we could do something similar in PHP (see https://gist.github.com/drock/6088355)?

**Comment by fvovan** [comment]
sgtm

**Comment by njam** [comment]
which one? :)

**Comment by fvovan** [comment]
Ah. I mean standart for now :) and if they decide to deprecate it we will be able to switch

**Pull request merged**
