### PR TITLE
Make sure daemon's monit entry for systemd does not output non-ASCII characters

### PR DESCRIPTION
**Pull request by ppp0**
We should disable output completely or disable non-ASCII characters.

### CODE REVIEW

**Comment by ppp0** [comment]
The only way to make this sure is to redirect the output to `/dev/null`. May be we could redirect also stderr's output? But if `systemctl status` fails, it's interesting if monit can provide us with details

@kris-lab agree?

**Comment by kris-lab** [comment]
Did you try to redirect all to `/dev/null` and see what is the exit code? I think `monit` checks the exit code and not the stdout/err output?

**Comment by ppp0** [comment]
I did, and yes, monit checks the exit code - which is unaffected by stdout/stderr output

My question is: shall we dump all output to /dev/null or just stdout?

**Comment by kris-lab** [comment]
It depends if `stderr` contains non-ASCII characters. If yes, then both should to the null/

**Comment by ppp0** [comment]
I don't know how to get `systemctl` to output something to stderr...
I guess we can safely dump both stderr and stdout.

We're really interested in the exit code only here

@kris-lab please review

**Comment by kris-lab** [comment]
ok, lgtm, works for me.

**Pull request merged**
