### PR TITLE
systemd: Use configuration files instead of symlink for units dependencies

### PR DESCRIPTION
**Pull request by tomaszdurka**
I've played a bit more with systemd and found that some of the links from wants/requires directories (those manually created) are removed in chains - systemd thinks they are not needed anymore.

I will rework module to work on `/etc/systemd/system/{$service}.d/foo.conf` files.

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@kris-lab or @ppp0 please review

**Comment by njam** [comment]
lgtm

Maybe call `systemd/templates/conf` rather `systemd/templates/unit.erb`?

**Comment by tomaszdurka** [comment]
Test passed, there was problem with CI cleaning the vagrant env. Is that actually a problem for @cargomedia/devops ?

**Comment by tomaszdurka** [comment]
@njam please review or delegate

**Comment by njam** [comment]
lgtm

**Pull request merged**
