### PR TITLE
Remove no-provision on snapshot restore

### PR DESCRIPTION
**Pull request by ppp0**
Follow up of #1589

### CODE REVIEW

**Comment by ppp0** [comment]
otoh, we had a "successful" build last night, without network failures. Only "real" failures were recorded. Could it be that all went fine because I did a "clean install" of the proxy, ie, full vagrant destroy, cache folder reset? Or it could just be good luck. At any rate, the full build only took 6hrs42min

**Comment by kris-lab** [comment]
Agree it look not relevant anymore. For last days we have failing specs, but not related to network issues, also not related to snapshot restore and also seems like cache/polipo works fine.

I would close it for now in favor of:
- https://github.com/cargomedia/puppet-cargomedia/issues/1645
- https://github.com/cargomedia/puppet-packages/issues/1580

**Comment by kris-lab** [comment]
Let's remove restart on polipo module and close this PR.

**Comment by kris-lab** [comment]
Follow up https://github.com/cargomedia/puppet-packages/pull/1599

**Pull request closed without merging**
