### PR TITLE
Make mongorc.js root only executable

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
Let's also make it root-only readable?

**Comment by kris-lab** [comment]
@njam ?

**Comment by njam** [comment]
Shouldn't it be 0700 ?

**Comment by kris-lab** [comment]
Uppsss:)

@njam please re-review

**Comment by njam** [comment]
lgtm, let's wait for the build (why did it fail before?)

**Comment by kris-lab** [comment]
Not sure, let's wait for build. Looks like some timing problem... replica not ready?

**Pull request merged**
