### PR TITLE
Set "limit_nofile" for cm_janus' daemon

### PR DESCRIPTION
**Pull request by tomaszdurka**
value: 20'000

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by tomaszdurka** [comment]
retest this please

**Comment by njam** [comment]
retest this please
 Hide all checks

**Comment by tomaszdurka** [comment]
retest this please

**Comment by njam** [comment]
lgtm

**Comment by tomaszdurka** [comment]
test finally passed ;)

**Pull request merged**
