### PR TITLE
Introduce configurable redirects for cm::vhost

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
Part of https://github.com/cargomedia/puppet-cargomedia/issues/613

@njam please review.. 

I'm not sure if a redirect should listen on port `443`, too - it probably should?

**Comment by njam** [comment]
- Should work opposite: There should be a list of `redirects`, which is a list domains that will redirect back to the original domain.
- Redirect should be for port 80 only (it's merely about typos, and we don't want to buy certs)

**Comment by ppp0** [comment]
* ooops
* ok

@njam please review

**Comment by njam** [comment]
- The https-redirect should also be applied for the original domain if $redirect is present? (add a spec?)

**Comment by ppp0** [comment]
makes sense makes sense
please review @njam

**Comment by njam** [comment]
Looks good!

**Pull request merged**
