### PR TITLE
Add nginx module support for Ubuntu

### PR DESCRIPTION
**Pull request by ppp0**
For now, we do not support Nginx for Ubuntu, but for testing Janus architecture it would be useful for Browser end-point of Janus testing architecture.

### CODE REVIEW

**Comment by ppp0** [comment]
Support for Debian Jessie is there and tested, though. Expected to be trivial

@kris-lab please review

**Comment by kris-lab** [comment]
Spec fails. Did it work for you locally?

**Comment by ppp0** [comment]
Problem with deb packages.. Supported is
```
Ubuntu:

Version	Codename	Supported Platforms
12.04	precise	x86_64, i386
14.04	trusty	x86_64, i386, aarch64/arm64
15.10	wily	x86_64, i386
16.04	xenial	x86_64, i386
```

Trying to see what fits to `15.04`

**Comment by ppp0** [comment]
`vivid` also present, though not officially listed

**Comment by ppp0** [comment]
@kris-lab much better now - please review

**Comment by kris-lab** [comment]
Yes, let's remove `notify{}`. 

Rest looks very good.

**Comment by ppp0** [comment]
ooops, of course :)

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
