### PR TITLE
cm::services::janus: Expect boolean value for recording_enabled

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
Closes https://github.com/cargomedia/puppet-packages/issues/1210

**Comment by tomaszdurka** [comment]
Removed your comment about closing #1210. Guess mistype.

**Comment by tomaszdurka** [comment]
Closes #1211

**Comment by njam** [comment]
How about also using boolean for the plugins' signatures? I think it will be easier if we have the same everywhere.

**Comment by tomaszdurka** [comment]
I've came back to separating issues.

@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
