### PR TITLE
Jessie for some minor modules

### PR DESCRIPTION
**Pull request by ppp0**
Part of #1346 

* irqbalance
* lame
* percona_toolkit
* sudo
* timezone
* ulimit
* uglify
* vim

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
2 specs  failed because of network (github?) issues...
merged upstream, now expecting to pass

@njam when done, could you give our ok, please (I find it hard to call for a review here)

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
