### PR TITLE
Remove Wheezy Support

### PR DESCRIPTION
**Pull request by ppp0**
Part of https://github.com/cargomedia/roadmap/issues/95

### CODE REVIEW

**Comment by ppp0** [comment]
Build will take *some* time... Paired w/ @kris-lab

**Comment by kris-lab** [comment]
Failed specs:
````
Finished in 11 hrs 59 mins 28 secs.
Failure! 334 specs run, 11 failures (1380 examples, 16 failures)
Failed examples:

    cron::monit Command "monit summary" stdout should match /cron.*[Running|Status ok]/
    cron::monit Command "monit summary" stdout should match /cron.*[Running|Status ok]/
    gearman::server Command "monit summary" stdout should match /gearman-job-server.+[Running|ok]/
    memcached Process "memcached" user should eq "nobody"
    memcached Process "memcached" args should match /-c 99\b/
    mms::backup Command "monit summary" stdout should match /[Process|Program] 'mms-backup'/
    mms::monitoring Command "monit summary" stdout should match /[Process|Program] 'mms-monitoring'/
    monit alerting Command "grep -c "Description: monitor action done" /var/mail/nobody" stdout should match "1"
    pulsar_rest_api Command "monit summary" stdout should match "pulsar-rest-api"
    puppet::puppetfile File "/tmp/foo/modules/mysql/metadata.json" content 
    puppet::puppetfile Command "cd /tmp/foo && librarian-puppet config" stdout 
    puppet::puppetfile Cron 
    puppet::puppetfile File "/tmp/foo/modules/mysql/metadata.json" content 
    puppet::puppetfile Command "cd /tmp/foo && librarian-puppet config" stdout 
    puppet::puppetfile Cron 
    vagrant::plugin Command "vagrant plugin list" stdout 
```

**Comment by kris-lab** [comment]
The source of all specs failing due to `monit summary` is related to @tomaszdurka proposition at https://github.com/cargomedia/puppet-packages/pull/1523 and introduced in meantime here https://github.com/cargomedia/puppet-packages/commit/14c6ec76f8eb57dcbceab1c0e899ae03930653a9

As the result we have multiple failing specs. So far it was working by chance I would say.

Also we should cleanup production entries.

**Comment by kris-lab** [comment]
@tomaszdurka I will merge your https://github.com/cargomedia/puppet-packages/pull/1523 into this PR + I will cleanup all affected specs!

**Comment by kris-lab** [comment]
@tomaszdurka thanks for notice about https://github.com/cargomedia/puppet-packages/pull/1498

I think we have many many conflicts at the moment. I will try to apply all needed changes to make specs running and then I would say we will merge https://github.com/cargomedia/puppet-packages/pull/1498

**Comment by ppp0** [comment]
@kris-lab please review. I found out that the new-style deb package, aka systemd-enabled, plain ignores our request to stop the service. That was the reason for not being able to stop as thought. Still, I believe it is good to modify the /etc/init.d script to a dummy

**Comment by ppp0** [comment]
@kris-lab please review only this commit: https://github.com/cargomedia/puppet-packages/pull/1524/commits/1ea22be6fedfca501f2e825e1d10c027c0860e20

**Comment by kris-lab** [comment]
@ppp0 perfect!

**Pull request merged**
