### PR TITLE
Re-add polipo and restart it at every snapshot restore

### PR DESCRIPTION
**Pull request by ppp0**
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1594

### CODE REVIEW

**Comment by ppp0** [comment]
I'm now merging this and starting a full build on ci
cc @kris-lab

**Comment by ppp0** [comment]
vagrant destroy everywhere needed to enable the cache

**Comment by njam** [comment]
You're restarting polipo in the puppet provisioner. I thought provisioners are not running on "snapshot go"?

**Comment by ppp0** [comment]
true, we switched that provisioning off :( - I was originally aiming at the shell provisioner, actually, puppet should not do anything if the state's not modified. 

The shell script, though, has been changed. Now we check if puppet is installed (https://github.com/cargomedia/puppet-packages/blob/master/scripts/puppet-install.sh#L15) and if it is, nothing happens. We were observing issues with a run condition for dpkg which should not be the case anymore..

Let's remove `--no-provision` from `snapshot restore``

**Pull request merged**
