### PR TITLE
Make puppet::db package ready once present

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
As discussed I think this is good, it might also solve our vagrant provisioning problems for puppet master.

Maybe consider using `grep -w $PID`
```
     -w, --word-regexp
             The expression is searched for as a word (as if surrounded by
             `[[:<:]]' and `[[:>:]]'; see re_format(7)).
```

Linting fails!

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
retest this please

**Comment by tomaszdurka** [comment]
Changes introduced in this pull-request are not needed. Main problem of puppetdb is polipo proxy.

**Pull request closed without merging**
