### PR TITLE
Increase monit's default load alerting thresholds

### PR DESCRIPTION
**Pull request by njam**
See e.g. http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages
Related to https://github.com/cargomedia/puppet-cargomedia/issues/659

@cargomedia/devops wdyt?

### CODE REVIEW

**Comment by ppp0** [comment]
if it helps, it's good - the topic is complex!

**Comment by njam** [comment]
So to summarize: a load of 1 means that the CPU is working at full capacity all the time, but no processes are waiting for execution time. Of course each processes' need of CPU calculations fluctuates a lot, so it can happen that many processes wait for CPU execution (number of processes in the run queue).

I've now reduced the 15 mins threshold to 0.8.
But for 1 minute we can go up to 5, and for 5 minues up to 2.

@cargomedia/devops wdyt?

**Comment by ppp0** [comment]
It's ok for me

**Comment by tomaszdurka** [comment]
Ok with me (reading up your linked resources).

**Comment by kris-lab** [comment]
sgtm

**Pull request merged**
