### PR TITLE
Optionally compile Janus and plugins from source

### PR DESCRIPTION
**Pull request by dergraf**
The tests for the plugins/transports are currently NOT using a source install.

@kris-lab, @njam, @ppp0

### CODE REVIEW

**Comment by njam** [comment]
- janus/manifest/init.pp: When installing from source we will install the version from `janus::version::number`, but never check for updates (the `helper::script`'s `unless` is just `ls /usr/bin/janus`). I would suggest these changes:
 - Combine $version and $use_src into one parameter ($src_revision)
 - Use `git::repository` to check out a git clone of the repo at a specific revision
 - Trigger compilation (which can be `helper::script`, or better just `exec`) whenever the repo changes (use `notify` from `git::repository`)
- janus/manifests/plugin.pp: Same
- I'm not too fond of this `janus::version::number` mechanism - it's kind of magic - and will apply to all resourced related to janus.
 - How about for the plugins having two params: $src_revision, $janus_src_revision and then explicitly passing it along?
- janus/manifests/service.pp: Can we always use `daemon`?
 - The `service`'s `subscribe` should also be present for the non-src case (when using `daemon`)
 - Maybe this resource can be completely inlined into `janus`, which will simplify things further
 - I suggest we **upgrade janus to a version with log file**. Otherwise everything will get overcomplicated. Could you build the appropriate DEBs - then I can test it in a local VM, and if it works fine we can continue here?

**Comment by njam** [comment]
```
    exec { 'compile janus':
      path        => ['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin'],
      command     => template("${module_name}/install.sh"),
      unless      => 'ls /usr/bin/janus',
      timeout     => 900,
      refreshonly => true,
      subscribe   => Git::Repository['foo'],
    }
```

**Comment by ppp0** [comment]
Also do not forget to 
>Add janus config file override, specs, re-add logging

(from #1080)

**Comment by ppp0** [comment]
paired w/ @dergraf 
@njam please review
@kris-lab cc

**Comment by dergraf** [comment]
yay!

**Comment by njam** [comment]
Looks very good!

- manifests/init.pp: Let's use mode `0644` also for directories - puppet automatically converts to `0755` - makes it easier imo to be consistent (the `cert.pem` should not be executable?).
- How about making those git repo paths more consistent (now `/opt/janus-gateway` and `/opt/janus/build/${name}`). Maybe just `/opt/janus/janus-gateway` and `/opt/janus/janus-gateway-audioroom`?
- plugin/rtpbroadcast.pp: Remove commented out code
- manifests/transport.pp: Remove this file?
- Make those `make install` execs `refreshonly` (so they don't execute every time)
- Installing janus or a plugin should trigger a service refresh (from both source and package installs)

**Comment by ppp0** [comment]
* agree, plus the `cert.key` should much less be world readable
* agree, some refactoring had to be done (introduce var for plugin repo name)
* yes
* see #epicfailure after https://github.com/dergraf/puppet-packages/commit/0ba73a8fc92446441395132925e335a898aaa2fd (had to https://github.com/dergraf/puppet-packages/commit/87ba10b96fc7d775b2ccf3f30ec57f6438512461) - can you suggest what went wrong? (Duplicate declaration)
* ok
* ok

**Comment by ppp0** [comment]
@njam please review (CI will take a while)

**Comment by njam** [comment]
Regarding 0ba73a8fc92446441395132925e335a898aaa2fd: Probably "janus::transport::websockets" should not include "janus" *and* the other way around? I would say transports should be optional/pluggable, so *they* should include janus?

**Comment by ppp0** [comment]
do you mean removing https://github.com/cargomedia/puppet-packages/blob/master/modules/janus/manifests/init.pp#L31 and https://github.com/cargomedia/puppet-packages/blob/master/modules/janus/manifests/init.pp#L32 ?

**Comment by njam** [comment]
yes, wdyt?

**Comment by ppp0** [comment]
sure.. well, that was easy :)

@njam please review

**Comment by njam** [comment]
lgtm

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
@njam seems good now, I'm merging

**Comment by njam** [comment]
lgtm

**Pull request merged**
