### PR TITLE
Daemon: Introduce runtime_directory args

### PR DESCRIPTION
**Pull request by ppp0**
Needed in #1243

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
- modules/daemon/templates/sysvinit.sh.erb: formatting

**Comment by kris-lab** [comment]
The rest looks good. However we grow the `daemon` a lot at the moment, which was not a goal.

**Comment by ppp0** [comment]
Agree. I see even more troubling issues coming toward us, see https://github.com/cargomedia/puppet-packages/issues/1424#issuecomment-237185220

**Pull request merged**
