### PR TITLE
Reorder dependencies in dyndns module

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab I noticed some things that could be named bugs :)

@kris-lab please review

**Comment by kris-lab** [comment]
Specs have to be updates as well.

**Comment by ppp0** [comment]
oops :) - @kris-lab please re-review

**Comment by kris-lab** [comment]
lgtm, does it require any cleanup on production now?

**Comment by ppp0** [comment]
yes, the directory `/etc/dyndns_updater` has to be purged. Production being `mandrill`, I can easily supervise it

**Pull request merged**
