### PR TITLE
Monit/daemon cleanup

### PR DESCRIPTION
**Pull request by tomaszdurka**
Followup from https://github.com/cargomedia/puppet-packages/pull/1497

- Cleanup daemon monit entry template (`monit.systemd.erb` unused)
- Purge monit entry directory

cc @ppp0

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by ppp0** [comment]
Sorry this is conflicting with our work on https://github.com/cargomedia/puppet-packages/issues/1524
Please hold on

**Comment by njam** [comment]
Ok let's wait for #1524

**Comment by kris-lab** [comment]
I will close this ticket. Changes in daemon affects multiple modules/specs and I am gonna resolve this issues on https://github.com/cargomedia/puppet-packages/pull/1524

@tomaszdurka can I close it?

**Comment by njam** [comment]
Let's close it once #1524 is merged, then we can verify everything here is resolved again?

**Comment by ppp0** [comment]
Closing

**Pull request closed without merging**
