### PR TITLE
Remove Wheezy references / Deprecate php <5.6

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab @njam please review

**Comment by njam** [comment]
I thought we will go through wheezy references in all puppet modules together and remove everything in one go. This is only part of it. What's your plan? Do you want to do it in multiple PRs and do code reviews?

**Comment by ppp0** [comment]
What do you suggest in detecting php versions <5.6 ?

**Comment by kris-lab** [comment]
@ppp0 let's have a pairing session and remove all in one go as suggested by @njam

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by ppp0** [comment]
closing in favour of #1524

**Pull request closed without merging**
