### PR TITLE
Beautify supported OS output and vm name

### PR DESCRIPTION
**Pull request by ppp0**
Pedantic but friendlier on the eyes and easy to accomplish

### CODE REVIEW

**Comment by ppp0** [comment]
@tomaszdurka please review :)

**Comment by njam** [comment]
Nooooo - we deliberately removed similar code because it adds unnecessary extra complexity. Especially with a switch/case…
Let's focus on more meaningful things instead!

**Comment by ppp0** [comment]
ok I will shut my eyes when spec testing

**Comment by njam** [comment]
```ruby
ruby -e 'system("say \"0 failures\"")'
```

**Comment by ppp0** [comment]
Now you introduce platform-specific code!

**Comment by njam** [comment]
`\a` doesn't work on OSX :(

**Pull request closed without merging**
