### PR TITLE
Refactor/rename cm::services::webserver

### PR DESCRIPTION
**Pull request by ppp0**
what this class does is very useful, but not a webserver proper

I propose `cm::services::server_status`

needs a couple of refactorings here and there

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
Shouldn't this be the other way around?
- vhost resource should require `nginx` (probably already does?)
- nginx resource should require `nginx::bipbip_entry`

or are there cases where we want nginx *without* the bipbip entry?

**Comment by njam** [comment]
@ppp0 Wdyt?

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
