### PR TITLE
Upgrade cm-janus

### PR DESCRIPTION
**Pull request by tomaszdurka**
- Adjust config

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam 

I am not sure what kind of flexibility we want here.
Should we:
- have nice value configurable (as is in pull-request)?
- have param for each of the commands?
- skip nice value in default command and only set it via command params? (as in previous point)

**Comment by njam** [comment]
One value for all commands should be fine. lgtm

**Comment by tomaszdurka** [comment]
We need to orchestrate this with SK release.

**Comment by tomaszdurka** [comment]
Actually this change is only related to incoming npm package release (ignore sk part).

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by kris-lab** [comment]
I think in `mjr2webm` we should swap audio and video paths?
```
echo "Usage: mjr2webm [--ffmpeg-params <ffmpeg-params>] <video-mjr-source> <audio-mjr-source> <output-file>"
```

**Comment by kris-lab** [comment]
ok, lgtm

**Comment by tomaszdurka** [comment]
Depends on #1128

**Comment by kris-lab** [comment]
Please update cm-janus config.

**Comment by tomaszdurka** [comment]
@kris-lab please final review

**Comment by kris-lab** [comment]
lvgtm

**Pull request merged**
