### PR TITLE
BO-22 Add recommended proxy settings for youtrack API

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
according to https://www.jetbrains.com/help/youtrack/standalone/2017.1/Reverse-Proxy-Configuration.html#Nginx_Config

@kris-lab please review
@njam fyi

**Comment by kris-lab** [comment]
As discussed the `vhost` name for `nginx` location is hardcoded in `jetbrains::youtrack` class, but finally formed in `jetbrains::application`. This is bigger topic for `nginx` refactoring.

I am ok to merge this

**Comment by kris-lab** [comment]
@njam let's wait for build and merge if this is urgent for you

**Comment by njam** [comment]
Not urgent, but would be great to have before Monday.

**Comment by kris-lab** [comment]
@njam please let us know if the error still appears

**Pull request merged**
