### PR TITLE
Manage bipbip user home directory

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by njam** [comment]
lgtm, add a spec assertion?

**Comment by kris-lab** [comment]
@njam please review;

Build are super slow; each time vagrant box is destroyed! Did we change that?

Also maybe good otpion would be `docker.io`?

**Comment by njam** [comment]
Use this?:
```
describe user('root') do
  it { should have_home_directory '/root' }
end
```

About destroying see https://github.com/cargomedia/puppet-packages/pull/816#issuecomment-70376848

screen shot 2015-01-19 at 10 57 26

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
