### PR TITLE
Move packages from cargomedia/puppet-cm repo

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
Looks good!

(Some specs would be good, but we can add them later)

**Comment by tomaszdurka** [comment]
Thought the same on the other hand it's mostly set of other packages. Maybe except stream and webserver.

I will add some later on.

**Pull request merged**
