### PR TITLE
Use matrix auth in jenkins

### PR DESCRIPTION
**Pull request by njam**
Closes https://github.com/cargomedia/puppet-cargomedia/issues/727

@ppp0 please review

### CODE REVIEW

**Comment by ppp0** [comment]
I reckon you tested this?
LGTM

**Comment by njam** [comment]
retest this please

**Comment by njam** [comment]
retest this please

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
Jenkins had 404 for debian's apt package.
Tests succeeded locally, will merge.

**Pull request merged**
