### PR TITLE
Cron job verbosity for satis

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
To find clues about what makes satis cron job fail, let's grab the output and attach it to cron's output

@njam agree?

**Comment by njam** [comment]
Is there a simple way to store it in a bash variable?

**Comment by ppp0** [comment]
A multi-line output you mean? - a single tmpfile not good?

**Comment by njam** [comment]
I thought about something like `foo=$(command) || echo "${foo}"`. So we don't need a file.
But if it's not easily possible then file is good as well!

**Pull request merged**
