### PR TITLE
Install pulseaudio service with optional modules

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@ppp0 not sure about that... wdyt? See usage https://github.com/cargomedia/puppet-cargomedia/pull/1214/files#diff-a9afb52964c3a1204622d9848dd524bcR27

**Comment by ppp0** [comment]
lgtm
what you don't like?

**Comment by kris-lab** [comment]
I had a thought that maybe it should be proxied from `pulseaudio::service` to `pulsaudio` which would install it. However it is overcomplicated, so if you agree I can merge this.

**Comment by ppp0** [comment]
I agree it'a bit of a a mess. We configure modules in the service. Otoh, service is non-standard handling (normal is autorespawn and all automagic).. 

May be the naming is unfortunate and should reflect our application somehow? I don't know. Let's see how far we get with this now

**Pull request merged**
