### PR TITLE
Add retryDelay configuration option for cm-janus

### PR DESCRIPTION
**Pull request by tomaszdurka**
Depends on https://github.com/cargomedia/cm-janus/pull/273

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
lgtm

**Comment by tomaszdurka** [comment]
retest this please

**Comment by ppp0** [comment]
looks like an issue on nodesource - let's wait

**Comment by njam** [comment]
@vogdb shouldn't cm-janus expect *seconds* as a unit? By using [SI units](https://en.wikipedia.org/wiki/International_System_of_Units) any ambiguity can be avoided.

**Comment by vogdb** [comment]
@njam currently it expects milliseconds as units. Shall we convert it to seconds? Agree that for this task seconds are more appropriate.

**Comment by njam** [comment]
Yes, let's use SI units in all public APIs!

**Comment by vogdb** [comment]
ok then cargomedia/cm-janus#285

**Comment by tomaszdurka** [comment]
@vogdb please review

**Comment by vogdb** [comment]
lgtm

**Pull request merged**
